whole-tale/girder_wholetale

plugin_tests/dataone_register_test.py

I noticed I left some debugging print statements in the tests. This removes them.

Remove Print Statements from Tests

---

server/dataone_register.py
server/rest/harvester.py

The verification steps are really not necessary and slow down registration and listing of files in dataone packages. Some casual benchmarking reveals a ~ 7x performance increase

Remove verification steps in register and listFiles endpoints

---

plugin.cmake
plugin_tests/dataone_upload_test.py
server/dataone_upload.py

This PR adds functionality for uploading a single file with metadata to a DataONE member node. There are additional functions that support creating metadata describing the file of interest. Note that this doesn't include an endpoint for reaching this code. Instead, this will be used internally by a publishing endpoint.
This corresponds to issue #73 
The unit tests are going to fail on this branch when run through CircleCI. The d1_python library that supports python 3 has not been released yet and cannot be obtained via pip. I've made modifications to the package on my local machine to support the python 3 commit to keep developing. When running the tests on my local environment, they pass. This branch should not be merged to master until the d1_python library is ready and fully …

Add Support for Uploading a File and Metadata

---

plugin_tests/dataone_package_test.py
plugin_tests/dataone_upload_test.py
server/dataone_register.py
server/dataone_upload.py
server/dataone_utils.py

Extends the endpoint to support files that are on the Girder file system. Also added some additional tests (which will still fail).
This corresponds to issue #77

Adds Support for Uploading Local Girder Files

---

server/__init__.py
server/models/tale.py
server/rest/tale.py
server/schema/tale.py

This PR introduces new fields for the Tale model:
1. `iframe` - if set to True, it should indicate that the Tale can be embedded in an iframe.
1. `format` - specifies the current format of the Tale model. It can be used to automatically add or remove keywords from existing objects upon girder start, provided that `validate()` method of the Tale model was updated accordingly.

Add new fields for Tales: iframe and format

---

plugin_tests/dataone_package_test.py
plugin_tests/dataone_upload_test.py
requirements.txt
server/dataone_package.py
server/dataone_register.py
server/dataone_upload.py
server/utils.py

Changes in dataone_package.py:
I added a parameter to create_minimul_eml that holds any useful information about the globus description file. I made it a dict in case we need to add more parameters to beef the EML up rather than adding n function parameters. The only element in it is the file size.
I broke the code that was getting executed in the item loop into functions so that they can get called if there is a globus file.
I also broke the old md5 function up so that it can be used more independently elsewhere.
The biggest addition is `create_external_reference_file`. This is responsible for downloading the remote resource and getting it's md5. We download the file and store the bytes in a `NamedTemporaryFile`, and then compute the md5 of it.
Changes in dataone_upload.py
You'll see …

Add Support for A Globus/Remote File Descriptor

---

server/constants.py
server/models/tale.py
server/rest/tale.py
server/schema/misc.py
server/schema/tale.py
server/utils.py

This PR allows to create Tales with an array of objects ("folders" and "items") as a data source. 
For simplicity I created a hidden collection that will keep a copy of selected data and will be used as single mountpoint for FUSE filesystem. In the future that will also allow us to create copies of data selected from volatile storage (Home, Workspace), for now this should be disallowed though.
TODO:

[WIP] Allow to create Tales with multiple data sources. Fixes #96

---

server/schema/misc.py

This PR adds new `environment` field to `containerConfig` schema, which allows to pass env vars to containers.
Corresponding changes to gwvolman: https://github.com/whole-tale/gwvolman/commit/b4c068a0d81e19ff43602cf7ed5696e39d98297e

Environmental variables can be passed to a running Tale

---

plugin_tests/dataone_package_test.py
plugin_tests/utils_test.py
server/dataone_package.py
server/dataone_upload.py
server/rest/repository.py
server/utils.py

This commit regards adding a file to the data package that describes where each file came from on the WT system. This is needed so that when we import the package back into Whole Tale, we can create a proper directory structure.
In utils.py:
I added a function that removes keys from a dictionary.
In dataone_upload.py:
I created a function, `create_upload_file_paths` that is responsible for creating the paths file and uploading it to DataONE. When the EML is generated for this file, the size is needed so I propagated this change in `create_upload_eml`
In dataone_package.py
Made changes to add a section of EML that describes the paths file.
I also changed a few model access levels to READ instead of ADMIN.
Example JSON:
```
{"EB2006_5944_SN10472.zip": [
{"type": "collection", "object": …
```

Add File Description Paths

---

requirements.txt
server/constants.py
server/dataone_package.py
server/dataone_upload.py

requirements.txt:
I'm using pyyml now
constants.py
I found myslef duplicating the file name in a few places; if we start creating more we should just use a struct to hold them.
dataone_package.py
I removed the eml record for the old paths and globus reference file and added one for tale.yml. I also renamed a few functions.
dataone_upload.py
I removed `create_upload_remote_file` and refactored `create_upload_file_paths` to handle the yaml file. The yaml file is created by joining a series of dicts and dumping them (via the yaml library).
I didn't see an appropriate format type in DataONE so I set it to text.
An example package can be found below.
https://dev.nceas.ucsb.edu/#view/24375bfe-d2d4-4fa6-9998-b28aa0ee9b1f
Note that a known bug is the text after the remote file's name.`Polygon …

Create tale.yml File

---

server/models/instance.py

Since instance spawning is non blocking right now it shouldn't impact UX anymore.

Reenable http status check for instances. Fixes #114

---

circle.yml
plugin_tests/tale_test.py
server/models/tale.py
server/rest/tale.py

We currently allow to change Tale's `public` attribute via `PUT /tale/{id}`. We shouldn't be doing that... Nevertheless:
* I've modified the update method to detect whether `public` was flipped and now we apply ACLs properly. 
* Changing ACLs on Tale no longer fails if user has insufficient privilege to modify the underlying Image. I think it's more sane behavior since:
* we have only public Images right now,
* potentially not accessible Tale with non public Image is less crazy, than user making Image private without taking into account all the other public Tales that might be using it...

Fix toggling 'public' parameter on a Tale. Fixes #121, #16

---

plugin_tests/constants_test.py
plugin_tests/dataone_package_test.py
plugin_tests/dataone_upload_test.py
server/constants.py
server/dataone_package.py
server/dataone_upload.py
server/rest/repository.py

We need to let the user pick a license for their package. This adds a parameter to the package endpoint. The licenses are keyed in constants.py
Most of the change can be read by first looking at the changes in constants.py, then going to repository.py and following the call stack. You'll see that the license id persists up to EML generation.
Note that in dataone_package.py I re-arranged some of the EML generation function. Mostly putting the code below the function declarations.
This corresponds to issue #128

Add License Information to EML

---

plugin_tests/dataone_package_test.py
plugin_tests/utils_test.py
server/dataone_package.py
server/utils.py

Commit a56e6e4 has changes that stip html out of the girder item fields (or a string in general). Fixes issue #117 
I branched off of `dataone_publishing` which had a pending PR (e17de4e13cc19378b03310040127d0913f6fd99d) which is why you see it here. I didn't want to branch off of `master` because it would require merging after `e17de4e13cc19378b03310040127d0913f6fd99d` is accepted.

Strip HTML in EML

---

plugin_tests/dataone_package_test.py
plugin_tests/dataone_upload_test.py
server/dataone_package.py
server/dataone_upload.py
server/utils.py

This commit adds functionality for setting the rightsHolder field in the EML.
This is just the `userId` field from the jwt. Most of the changes are trickling this ID to all of the `generate_system_metadata` calls.
I noticed the email wasn't getting set in the EML, so I went ahead and added it (since we have it)
We were adding it to the Creator field, but it should also go in `Contacts`.
Here's a package that was created using code from this PR. 
https://dev.nceas.ucsb.edu/#view/664d9781-cd8a-43b4-9850-fb1e91a1e5a2

Set the rightsHolder in the EML

---

plugin_tests/image_test.py
plugin_tests/tale_test.py
server/constants.py
server/models/tale.py
server/rest/tale.py
server/schema/tale.py

This PR introduces Tale's `narrative`, i.e. a set of scripts/files/notebooks that is going to be injected into the working directory upon Tale instantiation. In case of '.ipynb' and '.Rmd' files we could default to opening them after start in Jupyter and Rstudio respectively.
This feature will be divided into three stages:
1. Adding `narrative` support in Tale model (this PR)
1. Injecting `narrative` content into Tale Instance (PR to gwvolman)
1. UI modification, that would allow users to use `narrative` (PR to dashboard)
Stage 3 is outside of scope of v0.5 milestone. However, 1 and 2 will be used to address whole-tale/gwvolman#14

Add narrative to Tales

---

server/dataone_upload.py

When uploading a large number of files, the connection dies. If we take the performance hit of closing each connection we'll get reliable uploads.

Close Connection After Uploads

---

server/rest/publish.py

I should be extracting `_id` out of the girder token rather than passing the whole dict to the job. Same with `user`.

Extract the ID out of the girder token and user structure

---

server/rest/publish.py

Instead of parsing the mongo entries out of the Tale dictionary and passing it to the worker, pass the TaleID and load the Tale from inside the worker.

Pass TaleID to Worker Instead of Tale Dict

---

server/constants.py
server/models/instance.py

Avoids the hassle of reconstructing instance url on Girder side. gwvolman task has all the required information to construct it during the service creation.

Construct instance url in gwvolman, rather than in Girder

---

plugin_tests/data/test_find_resource_pid.txt
plugin_tests/data/test_get_package_list_flat.txt
plugin_tests/data/test_get_package_list_nested.txt
plugin_tests/data/test_list_files.txt
plugin_tests/dataone_register_test.py
server/__init__.py
server/constants.py
server/lib/dataone/dataone_provider.py
web_client/templates/configView.pug
web_client/views/ConfigView.js

This PR reverts behavior for lookup to always querying DataONE with whatever we pass to `GET /repository/lookup` instead of trying to determine origin using heuristics.

Explicitly query DataONE with every string that's passed to lookup. Fixes #176

---

plugin.cmake
plugin_tests/integration_test.py
server/__init__.py
server/lib/dataverse/integration.py
server/rest/integration.py

This PR creates a simple endpoint that accepts requests coming from Dataverse external tools and return 303 to a proper dashboard route with an encoded datafile information.
Suggested test:
1. Run girder with env `DASHBOARD_URL` set to your dashboard instance (needs https://github.com/whole-tale/dashboard/pull/287 and https://github.com/whole-tale/girder_wholetale/pull/175)
1. Run a dataverse with a ext tool integration pointing to `<your_girder>/api/v1/integration/dataverse` (remember to set `DATAVERSE_URL` in `wholetale` plugin's config)
1. See the magic happen!

Dataverse External Tools integration

---

plugin_tests/dataone_register_test.py
plugin_tests/dataverse_test.py
plugin_tests/harvester_test.py
server/__init__.py
server/constants.py
server/lib/dataverse/provider.py
web_client/templates/configView.pug
web_client/views/ConfigView.js

Apart from deriving a list of Dataverses from https://services.dataverse.harvard.edu, this PR allows to manually add specific Dataverse Instances.
Suggested test:
1. set DATAVERSE_URL to `https://services.dataverse.harvard.edu/miniverse/map/installations-json`
1. set DATAVERSE_EXTRA_HOSTS to `["https://dev1.dataverse.org"]`
1. Verify that `GET /repository/lookup` for `dataId=["https://dx.doi.org/doi:10.7910/DVN/TJCLKP", "https://dev1.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/EPNUKP"]` results in Data Map containing two entries with `repository == Dataverse`

Allow to manually add supported Dataverse instances

---

plugin_tests/basic_test.py
plugin_tests/constants_test.py
plugin_tests/dataverse_test.py
plugin_tests/instance_test.py
requirements.txt
server/__init__.py
server/constants.py
server/rest/wholetale.py
web_client/collections/index.js
web_client/models/index.js
web_client/templates/configView.pug
web_client/views/ConfigView.js
web_client/views/InstanceListWidget.js
web_client/views/body/LaunchTaleView.js

Additionally allows to save empty config form and defaults are now respected if empty values are provided.
To test:
1. Setup clean environment
1. Navigate to https://girder.local.wholetale.org/#plugins/wholetale/config
1. Verify that *tmpnb*, *priv/pub key* fields are gone.
1. Hit 'Save'
1. Verify that defaults are respected, by:
- reloading plugin config and see if the form updates with new values
- (optional) trying to launch more than 2 instances
- (optional) trying to register something from dataverse.harvard.edu

Remove obsolete config options, fixes #185

---

plugin_tests/data/dataverse_lookup.txt
plugin_tests/data/test_list_files.txt
plugin_tests/dataverse_test.py
server/lib/resolvers.py
server/rest/repository.py

DOI often points to a location that returns `30x` code, that potentially resolves to another location returning `30x`... A good example:
```
$ curl -s -IL https://hdl.handle.net/1902.1/22315  |grep "HTTP\|Location"
HTTP/1.1 303 See Other
Location: http://thedata.harvard.edu/dvn/study?globalId=hdl:1902.1/22315
HTTP/1.1 302 Found
Location: https://thedata.harvard.edu/dvn/study?globalId=hdl:1902.1/22315
HTTP/1.1 302 Found
Location: https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/22315
HTTP/1.1 200 OK
```
This PR tries to resolve DOI until 200 is reached. It also uses `HEAD` instead of `GET`, which should be more efficient in case DOI resolves with a big object.
Testing:
1. Try as many different DOIs as you can think of.

Resolve chained redirections in DOIs

---

plugin.cmake
plugin_tests/repository_test.py
server/rest/repository.py

Girder throws nice errors now. They're not parsed and showed to the user in the dashboard, but 500s weren't either.

Wrap errors in lookups with RestException. Fixes #189

---

server/lib/__init__.py
server/lib/http_provider.py

Most of http servers are clever enough to serve you compressed content, and most clients are clever enough to decompress it on the fly. On the other hand our FUSE is not that clever... This PR defaults to requesting plain, uncompressed content over http(s).
To test:
1. Register raw file from e.g. GitHub
2. Create a Tale with it, run it.
3. Verify the content is all there.
Thanks to @MatthewTurk for immediately knowing what's wrong and speeding up the debug process.

When requesting files via http do not accept compression. Fixes #191

---

plugin_tests/instance_test.py
requirements.txt
server/models/instance.py

This should be tested on `.dev` deployment before merging.
Test case:
1. Deploy on `.dev`, either via custom image or by using bind mount
1. Launch any tale
1. Confirm that `~girder/.girder/logs/error.log` doesn't have requests log
1. Confirm that `~girder/.girder/logs/info.log` has some output from `_wait_for_server`

Switch to urllib for testing instance readiness. Fixes #201

---

plugin_tests/tale_test.py
server/models/tale.py
server/rest/tale.py
server/schema/misc.py
server/schema/tale.py

Converts `involatileData` to use `dataSet` instead of custom format.
1. Create a Tale with at least one folder/item as external data
2. Use `GET /tale/{id}` to check whether `involatileData` matches the new format.
3. (Optionally) Look at existing Tales using `GET /tale` and see if `involatileData` migrated cleanly.

Use dataSet object as 'involatileData'. Fixes #209

---

plugin_tests/tale_test.py
server/lib/dataone/register.py
server/models/instance.py
server/models/tale.py
server/rest/tale.py
server/schema/tale.py

Published Tales should have a record that they were
1. Published
2. Have a DOI
3. A URI to locate the Tale
The following parameters are added to the Tale
`published`
`doi`
`publishedURI`
The change in `server/lib/dataone/dataone_register.py` was done to satisfy the linter.
Using the Girder API,
1. Create a new Tale
2. Update the Tale, changing the values of `published`, `doi`, and `publishedURI`.
3. Get the Tale and confirm the changes were saved
I had issues squashing the previous merge commits, but was able to get the relevant changes into a single commit, [here](https://github.com/whole-tale/girder_wholetale/pull/203/commits/3a4eb478cc6447df96560a45e5f8248346f3437c)
I have some merge conflicts that I need to resolve before I can merge this PR conflict-free.
Right now I'd like a glace …

Add Additional Fields to Tale

---

server/schema/misc.py

It's a convenience that will save us a few calls to the db, e.g. while tackling https://github.com/whole-tale/dashboard/issues/368

Allow to specify model type in dataSetItem

---

plugin.cmake
plugin_tests/tale_test.py
plugin_tests/workspace_test.py
server/__init__.py
server/models/tale.py
server/rest/workspace.py

This PR introduces `GET /workspace` and `GET /workspace/{:id}` as a convenience method of retrieving workspace folder with a proper name and a `_modelType`. For rationale see https://github.com/whole-tale/dashboard/issues/364
1. Create a bunch of Tales
1. Using Girder's Swagger page call `GET /workspace`. Verify that:
* each returned object's `_id` corresponds to a proper folderId in `/collections/WholeTale Workspaces/WholeTale Workspaces`
* each returned name/lowerName corresponds to a Tale's title, rather than Tale's id.

Add 'workspace' resource. Fixes #225

---

plugin_tests/harvester_test.py
server/rest/dataset.py

It seems that `dataset` is the only model that uses a `modelType` field instead of a `_modelType` like everything else. Not sure what I had in mind when I wrote it down...

Use '_modelType' in dataset model for consistency

---

plugin_tests/tale_test.py
server/models/tale.py
server/rest/tale.py
server/schema/tale.py

This is alternative approach to fix #225. Instead of creating a separate `/workspace` endpoint, we might as well query Tales directly as long as we get what we need: the id of a workspace.
1. Create a bunch of Tales
1. Using Girder's Swagger page call GET /tale. Verify that:
each returned object's `workspaceId` corresponds to a proper folder `_id` in `/collections/WholeTale Workspaces/WholeTale Workspaces`.

Add 'workspaceId' reference to Tale model. Fixes #225

---

plugin_tests/dataset_test.py
server/__init__.py
server/rest/dataset.py

Allow to remove entries from user's `myData` via `DELETE /dataset/:id`
1. Register two datasets
2. Confirm they're linked to user model by using `GET /dataset?myData=true`
3. Use `DELETE /dataset/:id` with one of the ids from 2.
4. Confirm that `GET /dataset?myData=true` returns one dataset
Alternative:
1. Enable "Remove" in Manage > Data and see if it works :-)

Add a method for removing entries from the user's myData field

---

server/rest/image.py

Use proper queue.
1. Set up a proper docker swarm with at least one master and one slave.
2. Run celery_worker with proper queues on each of them (manager on master, celery on slave).
3. Build an image.

Ensure that images are build on head node. Fixes #237

---

server/lib/http_provider.py

This PR introduces 2 changes to http resolver:
1. *Content-Type* header is no longer a hard requirement for looking up urls, since we already default to `application-octet/stream` if header is not present during the registration stage.
1. Url provided by the user is checked for http redirects and only final url is used for creating a dataMap.
NOTE: This PR is necessary to properly recreate the LIGO Tale.
1. Try registering: `https://losc.ligo.org/s/events/GW170104/H-H1_LOSC_4_V1-1167559920-32.hdf5`

Http provider lookup bugfixes. Fixes #246

---

plugin_tests/workspace_test.py
server/rest/workspace.py

Workspace endpoints were returning raw, instead of filtered by user's access level, objects. It's fixed by applying native Folder's `filter()` method. This may (or may not) affect https://github.com/whole-tale/dashboard/pull/406.
1. Inspect output of `GET /workspace` and make sure:
1. `_accessLevel` is present
1. `access` is not present

Filter Workspace fields in a same way as Folders. Fixes #242

---

plugin_tests/tale_test.py
scripts/tale_acls_fix.py
server/models/tale.py

This PR:
1. Ensures that ACLs on `workspaceId`, `narrativeId` and `folderId` are the same as on Tale itself.
1. No longer changes ACLs on Images.
1. Disables automatic Tale format migration. Required changes are usually a one time things, and this adds unnecessary complexity to `Tale().validate()` method.
1. Create a private Tale as user A, put something into workspace directory.
2. Make it public.
3. Try running a Tale as user B.
4. Access Workspace and confirm it's readonly.

Set proper ACLs on Tale folders

---

server/rest/dataset.py

Change default sort order.
1. Register multiple datasets.
2. Navigate to Manage > Data
3. Confirm A->Z sorting

Default to ascending order for datasets. Fixes #257

---

plugin_tests/license_test.py
plugin_tests/tale_test.py
server/__init__.py
server/lib/license.py
server/models/tale.py
server/rest/license.py
server/rest/tale.py
server/schema/tale.py

This PR has two parts, which are separated into respective commits. 
The first adds a new field to the Tale, `license`. 
The second adds an endpoint that returns a list of supported licenses. I put three fields for each record:
1. The common name
2. The spdx
3. A compliant portion of the license needed to properly attribute a work
During the dev call about this feature, we decided that a URL would be the best approach however, I wasn't able to find a suitable endpoint that returned the text of a given license, and it seems that data repositories (Dataverse and DataONE) supply legal subsets of the license along with the URL. The text was taken from packages on DataONE however, similar text can be found across other repositories.
To Test Licenses:
2. Deploy
3. Visit …

Add Tale licenses

---

server/models/instance.py
server/rest/instance.py

Our current restart endpoint expects the `image` to have a `digest` field. @craig-willis' upcoming PR will move this to be a part of the `tale.imageInfo` object instead.
Furthermore, the `gwvolman` restart task assumes and injects the registry info (as a precaution to prevent arbitrary containers from launching). 
This quick hack updates the `PUT /tale/:id` endpoint to accommodate this change. This also temporarily strips out the registry info before sending it to `gwvolman`.
We should probably discuss the expected long-term format for these operations, as we seem to have digressed.
Prerequisites:
1. Have at least 1 running Tale image
2. Run https://github.com/whole-tale/deploy-dev/tree/repo2docker
3. Comment out or remove all calls to `/image/:id/build`, as this endpoint no longer exists …

Temporary hack to build up the correct image format when restarting

---

server/lib/globus/globus_provider.py

This time it wasn't that bad. Nevertheless, parsing html representation of something that should be accessible via API seems fragile. Not that Globus API can't suddenly change underneath us without any warning...

Update Globus wrt publish.globus.org recent changes. Fixes #263

---

server/lib/globus/globus_provider.py

1. Import Globus dataset (e.g. `doi:10.18126/M2301J`)
1. Using Girder UI, navigate to `/collection/WholeTale Catalog/WholeTale Catalog/Twin-mediated Crystal Growth: an Enigma Resolved` and confirm that `meta.identifier` is present and equal to `doi:10.18126/M2301J`
Note: Depends on #263

Set identifier on the root folder of imported Globus dataset. Fixes #261

---

server/rest/publish.py

We removed the need to specify the license in the publishing modal and endpoint. We also decided to hold off on the entry point idea.
This PR removes the license and optional prov field from the endpoint.

Remove the license and entry point parameters for the publishing endpoint

---

server/rest/publish.py

This PR removes the parameter that lets someone specify which files should be included in a published Tale.
Testing:
2. Deploy
3. See that the publish/dataone endpoint no longer has a field for itemIDs

Remove itemIds from the Publish Endpoint

---

plugin_tests/harvester_test.py
scripts/http_files_migrate.py
server/lib/http_provider.py
server/rest/dataset.py

Currently, files registered via the *http* provider end up within the root of the *Whole Tale Catalog*. Since we "reuse" Girder objects during the registration to avoid duplicates, it quickly leads to name collisions, e.g. if two users register a file called README.md, only one of those can be stored in WT.
In order to assign a pseudo-unique identifier to http resources we can map a url to a folder structure (using `/` as a separator) and register the file as a leaf item underneath it. E.g. 
- `http://example.com/level1/level2/file.zip` -> `/collection/WholeTale Catalog/WholeTale Catalog/example.com/level1/level2/file.zip`
- `http://use.yt/upload/4166454f` -> `/collection/WholeTale Catalog/WholeTale Catalog/use.yt/upload/4166454f/axis_test.zip` (uses `Content-Disposition` for deriving …

Sanitize location of http resources in WT Catalog. Fixes #193

---

plugin_tests/manifest_test.py
plugin_tests/tale_test.py
server/lib/manifest.py
server/rest/tale.py

This PR builds off of the work done in `tale_manifest` that creates a structured zip file that represents a Tale.
I'm not sure how to unit test this, but I'm open to suggestions.
To Use:
1. Create a tale with a workspace and external data
2. Navigate to the Girder API page
3. Scroll down to the export endpoint under tale
4. Paste your Tale ID in the box
5. Request the zip
6. Copy + Paste the curl command into the terminal
7. Add -JO before -X
8. Execute the command and unzip the Tale
To DO:

Refactor the export endpoint to conform to new spec

---

server/lib/manifest.py
server/rest/tale.py

While testing manifest export locally I found two issues:
1. We were trying to access workspace as an owner, which failed if you tried to export a Tale you didn't own.
2. A method responsible for identifying all the http files in the Tale's `dataSet` was hitting an infinite recursion loop if an http folder from the `dataSet` contained no items.
1. Deploy locally
1. Register Ligo Tale
1. Export Ligo Tale (without this PR zip is malformed...)

Manifest fixes

---

plugin_tests/dataset_test.py
server/rest/dataset.py

Since #266 HTTP resources end up in a deeply nested folder structure. This PR makes them easier to find if one still knows the url that was used during the registration. It can be potentially useful on the UI's catalog view to search by doi etc.
1. Deploy locally and register the Ligo Tale
2. Using swagger, call `GET /dataset` with `identifiers` equal to `["https://www.gw-openscience.org/s/events/BBH_events_v3.json"]`.
3. Confirm it return item named `BBH_events_v3.json`

Filter datasets by an external identifier. Fixes #276

---

server/lib/__init__.py
server/rest/dataset.py
server/rest/repository.py

This PR extracts some logic and functionality from `Repository` and `Dataset` resources, which shouldn't be there in the first place. As result, it's now possible to programmatically resolve and register DOIs without going through the REST layer.
It's basically a noop. It should be good to go if tests are passing.

Refactor code related to registration

---

plugin.cmake
plugin_tests/publish_test.py
plugin_tests/tale_test.py
server/models/tale.py
server/rest/publish.py
server/rest/tale.py
server/schema/misc.py
server/schema/tale.py

The current publishing implementation stores a single PID (DOI) on the Tale object, but allows the user to publish multiple times, losing track of previously published versions.  Supporting re-publishing of a Tale seems like a desirable feature, so this PR updates the Tale model and schema to support an array of objects representing published Tale packages.   I also changed the job creation to match the other gwvolman tasks (i.e., use `delay()`) 
To test:
* Checkout `dashboard` `dataone_publishing` (optional)
* Checkout `gwvolman` `dataone_publishing` (required)
* Publish a Tale
* Inspect the Tale object, note a single entry in `publishInfo`
* Publish Tale again
* Inspect the Tale object, note two entries with latest entry at the end

Add publishInfo as array

---

server/models/tale.py

It's possible to create a Tale with `config = None`. This probably should be prevented in a schema, but I'm not sure how.

Sanitize the tale['config'] so that it always has a value

---

server/lib/exporters/__init__.py
server/lib/manifest.py
server/rest/tale.py

This PR enables expanding Tale's dataSet folders into items recursively (similarly to the way we were treating folders created by HTTP(S) provider already).
1. Deploy locally
2. Register `doi:10.5065/D6862DM8`
3. Create a Tale and select `Humans and Hydrology...` as data source in Run > External Data
4. Export the Tale as BagIt
5. Verify that `manifest.json` in `aggregates` section and `fetch.txt` contain only files.

Allow to expand dataSet folders in the Tale's manifest

---

server/models/instance.py
server/rest/tale.py

Fixes #289.
To test:
* On a single-node and multi-node deployment
* Launch a new Tale, confirm the image build during instance launch succeeds
* Build an existing Tale, confirm the image build succeeds

Changed build_tale_image tasks to pass queue=manager

---

plugin_tests/manifest_test.py
plugin_tests/tale_test.py
server/lib/manifest.py
server/models/tale.py
server/schema/tale.py

The changes here switch the `authors` field from a string to a list of objects. The example was also updated for the swagger UI.
The infrastructure for handling _some_ object called 'authors' already exists, so the real changes were
1. Bumping the format up one version
2. Adding a validation check to make sure the `authors` field is a list
The most controversial part of this is setting the orcid field to `''` because we currently don't have knowledge of it in the `user` model.
The first change was to make the `@id` of the `createdBy` field the email of the Tale creator.
The second change was to add a method that loops over each object under the `tale['authors']` and create a section under `schema:authors` for them.
Potentially controversial: The `@id` and `orcid` fields are duplicated, …

Add Structured Multiple Authors to Tale. Fixes #272

---

plugin_tests/manifest_test.py
plugin_tests/tale_test.py
server/lib/manifest.py
server/models/tale.py
server/schema/tale.py

Reverts whole-tale/girder_wholetale#273.
Original PR should not have been merged until https://github.com/whole-tale/dashboard/pull/445 was merged too. It breaks Tale object handling on the UI side (every PUT/POST tale fails).

Revert "Add Structured Multiple Authors to Tale. Fixes #272"

---

plugin_tests/manifest_test.py
plugin_tests/tale_test.py
server/models/tale.py

This partially fixes problems described in (https://github.com/whole-tale/girder_wholetale/issues/297). It's better not to have an author, rather than had one with an invalid ORCID id.
NOTE: as a side-effect authors will be gone from Tale cards in the UI, by default

Don't default authors to creator

---

plugin_tests/instance_test.py
plugin_tests/tale_test.py
requirements.txt
server/lib/__init__.py
server/models/tale.py
server/rest/tale.py
server/rest/wholetale.py

In order to facilitate https://github.com/whole-tale/dashboard/issues/450, this PR introduces `dataSetCitation` field on a `Tale` object. It's regenerated every time Tale's `dataSet` changes.
During `PUT /tale/{id}` and `POST /tale` trigger an event that:
1. creates a set of DOIs based on `dataSet`
2. fetches citation string from DataCite
3. returns a Tale with an updated `dataSetCitation` field
1. Create a Tale with data registered using DOI
2. Confirm that Tale's `dataSetCitation` contains a citation.

Fetch a citation for dataSets every time Tale is updated. Fixes #291

---

plugin_tests/publish_test.py
server/rest/publish.py

We need to tell whether we're publishing to production or to development, so I added a flag to the dataone publishing endpoint.
Testing steps are [here]()
Linked issues is #302

Add production flag to publishing. Fixes #302

---

plugin.cmake
plugin_tests/notification_test.py
requirements.txt
server/__init__.py
server/models/instance.py
server/models/tale.py
server/rest/instance.py
server/rest/tale.py
server/utils.py

See the [Notifications design doc](https://docs.google.com/document/d/1IkvsZqxxlIBaxVLT1yb1kWtGyDuJRo8ZzT1hsqke_NE) for details.
Along with https://github.com/whole-tale/gwvolman/pull/75, this PR implements changes to how we handle task notifications and progress reporting for instance creation, restarting, and image building.
* Each logical task (which may be multi-job) creates a progress notification and passes the ID to each job via `girder_job_other_fields`. This results in the job object having a `wt_notification_id` field.
* Gwvolman (Celery) tasks use the internal `job_manager.updateProgress()` method to update per-job progress.
* A generic `updateNotification` event handler (event=jobs.job.update.after) updates a single progress notification based on the provided …

Unified notification support

---

plugin_tests/tale_test.py
server/models/instance.py
server/models/tale.py
server/rest/tale.py

Primarily during testing, I often want to build an image even if the workspace hasn't changed (e.g., the repo2docker image has changed).  Along with https://github.com/whole-tale/gwvolman/pull/76, this PR adds the `force` parameter to the `tale/{id}/build` endpoint.
To test:
* Build a Tale image
* Do not change the workspace
* Using the swagger API, GET /tale/{id}/build?force=false
* Note that the tale doesn't build because the workspace is unchanged
* Using the swagger API, GET /tale/{id}/build?force=true
* Note that the tale image rebuilds even though the workspace is unchanged.

Allow build if workspace hasn't changed

---

requirements.txt
server/lib/exporters/bag.py

This PR changes the export process to use the repo2docker version as configured in gwvolman. Depends on  https://github.com/whole-tale/gwvolman/pull/77

Use repo2docker version from gwvolman constants

---

plugin_tests/instance_test.py
server/models/instance.py
server/rest/instance.py

This PR converts `updateAndRestartInstance` to asynchronous method (we no longer `.get()` the task) and updates Instance status using event handler bound to `update_container` job.
1. ~(optionally) use this PR in combination with https://github.com/whole-tale/gwvolman/pull/66~
2. Create Tale, modify env, rebuild image.
3. Restart the Tale
4. Reload the dashboard (this is something that ultimately shouldn't be necessary)
5. Confirm that Tale/Instance icon in the right panel has a spinner.
6. Confirm that spinner disappears when container is restarted and that Run/Interact view points to a new container.

Change Instance status while the underlying container is updated

---

server/lib/exporters/bag.py

Fixes #309 
This PR:
* Removes the `template` and `buildpack` arguments from the repo2docker command template
* Mount `metadata/environment.json` to `data/workspace/.wholetale/environment.json` at runtime
* Quote volume paths to allow for spaces in paths
To Test:
* Export a Tale
* Run it locally and see that it works...

Remove template and buildpack arguments, move environment.json

---

server/utils.py

The original value of 10 days was intended to support the "past events" feature, which will not be implemented until v0.8.  For v0.7, set this to one hour.

Reduce notification expiration time

---

plugin_tests/tale_test.py
server/constants.py
server/models/tale.py
server/rest/tale.py
server/schema/tale.py
server/tasks/copy_workspace.py
setup.cfg

This PR implements required backend functionality for "Copy on Launch" feature. It:
1. adds `POST /tale/:id/copy` endpoint
1. introduces TaleStatus:
* `PREPARING` - workspace is being copied
* `READY` - workspace has been copied
* `ERROR` - workspace failed to be copied
1. Deploy https://github.com/whole-tale/wt_home_dirs/pull/22
1. Create a Tale (preferably as user A)
1. Upload/create some content in the workspace
1. Call `POST /tale/:id/copy` using API (preferably as user B)
1. Confirm that new tale is created and:
* it's not public
* it's created and owned by user issuing POST request (user B)
* its workspace has the same content as the original tale's workspace
1. UI can determine whether the operation of copying has finished by:
1. Listening for `job_status` event and filtering using …

Allow to copy Tales

---

server/models/instance.py
server/models/tale.py
server/rest/instance.py
server/rest/publish.py
server/rest/tale.py

If there's task running (e.g. launching a Tale) when the user logs out, the user's auth token is invalidated and any GirderClient usage (e.g. writing output to job logs) leads to task failure.
Generate dedicated user tokens to use inside jobs.
1. Checkout and run this branch locally
1. Login to the WholeTale Platform.
1. In a terminal window, follow logs from `celery_worker` container:
```
docker logs --tail=20 -f celery_worker
```
1. Launch a Tale (You should see a job running in `celery_worker`)
1. While the Tale is still launching, log out of the WholeTale Platform
1. You should see job continuing to run in `celery_worker` logs
1. Once `celery_worker` logs indicate that the Tale launched (Task gwvolman.tasks.launch_container is completed) log in to dashboard and confirm Tale is …

Use a dedicated token to intialize GirderClient in jobs. Fixes #311

---

server/lib/globus/globus_provider.py

Fixes a case when a citation was not created properly when the root of Globus dataset was added to external data
1. Register http://dx.doi.org/doi:10.18126/M2662X (Manage)
2. Create an empty Tale (Compose)
3. Verify that citation in Tale's metadata is empty ( Run > Metadata )
4. Add 'A Machine Learning Approach for Engineering Bulk Metallic Glass Alloys' to the Tale ( Run > Files > External Data)
5. Verify that Tale has following citation (Run > Metadata):
```
Wolverton, C. (2018) “A Machine Learning Approach for Engineering Bulk Metallic Glass Alloys.” Materials Data Facility. doi: 10.18126/M2662X.
```

Properly identify DOI for the root of a globus ds. Fixes #312

---

plugin.cmake
plugin_tests/data/dataverse_integration.txt
plugin_tests/data/tale_import_binder.txt
plugin_tests/import_test.py
plugin_tests/integration_test.py
plugin_tests/tale_test.py
requirements.txt
server/__init__.py
server/lib/dataverse/integration.py
server/rest/tale.py
server/tasks/import_binder.py

Default "Analyze in WT" workflow imports incoming dataset as an immutable, readonly data. In some scenarios (e.g. a Binder compatible collection of files published to Dataverse whole-tale/whole-tale#66) this behavior is undesirable. Data should be copied to the Workspace instead to allow user to modify the environment and/or the code.
1. Add a parameter `asTale` to `POST /tale/import` to indicate whether the dataset defined by `url` parameter should be imported as involatile data or copied to the workspace.
2. Importing as Tale is implemented as follows:
1. Register the dataset defined by the `url` in the Catalog
2. Create a `Session` with the content of registered folder from 1.
3. Create an empty `Tale`.
4. Copy data from WtDms (defined by the Session from step 2.) to the workspace …

Allow to import an external dataset as a Tale

---

plugin_tests/tale_test.py
server/models/tale.py
server/rest/tale.py

This PR adds the ability to change the environment of a Tale. This was done by moving the `imageId` into the Tale's modifiable fields. Because the request that is sent to girder has the new imageId encoded as JSON, we load the image before setting `tale['imageId']` which provides us with an ObjectID type rather than string. This is reflected in the unit tests where we need to create a new image rather than using a dummy string.
To Test:
2. Launch the dashboard
3. Navigate to a Tale's metadata page
4. Change the environment
5. Save
6. Refresh the page
7. Note that the environment has been saved.

Update the Tale's 'imageId' on PUT

---

server/models/instance.py
server/models/tale.py
server/rest/instance.py

Fixes #320.
To test:
* Start a tale
* Modify the environment and rebuild the tale
* Restart the tale
* Inspect the notification stream and confirm that the `resource` field for notifications with `type`  in `wt_create_instance`, `wt_build_image`,  and `wt_update_instance` contains the `tale_title` set to the title of the current tale.

Add tale_title to notification payload

---

server/lib/__init__.py

`update_citation` method was needlessly trying to resolve HTTP(S) resources via Datacite. Since each of HTTP(S) resources has a unique UUID (its url), it was generating numerous outgoing calls. That's no longer the case with this PR.
1. Deploy locally, register LIGO Tale.
2. Run `Copy on Launch` on LIGO Tale and confirm it starts new instance almost immediately.
3. Celebrate!

Do not try to resolve raw http resources via Datacite. Fixes #327

---

server/lib/dataverse/integration.py

`/compose` no longer exists. Analyze in WT is handled via `/browse` route. See https://github.com/whole-tale/dashboard/pull/465

Update Analyze in WT redirect per whole-tale/dashboard#465

---

server/lib/dataone/integration.py

Redirect users to browse instead of compose.
If you want to test this, then check the branch out visit
https://girder.local.wholetale.org/api/v1/integration/dataone?uri=doi%3A10.5063%2FF1639N12&title=Test%20Tile&environment=RStudio
Check to see that you end up on the browse page instead of compose.
Linked to #334

Update redirect URL

---

server/lib/exporters/bag.py

Fixes issue #341 
I couldn't think of a better way than list comprehension, which doesn't scale nicely as the number of additional files increases.
Output after this change:
```
"aggregates": [
{
"uri": "../data/workspace/AirTempHistoric.ipynb.txt"
},
{
"uri": "../data/workspace/fetch.txt"
},
{
"schema:license": "CC-BY-4.0",
"uri": "../data/LICENSE"
},
{
"@type": "schema:HowTo",
"uri": "../README.md"
}
],
```
2. Export a Tale to a bag
3. Check that the manifest correctly locates the top level README.md

Don't add ../data to README.md path

---

server/lib/exporters/__init__.py
server/lib/exporters/bag.py
server/lib/exporters/native.py

This change mostly pulls out some methods from the zip exporter and puts it in the `TaleExporter` class so that it can be used by the bag exporter. Fixes issue #337
2. Add some files to the workspace
3. Export with zip and bag
4. Note that the manifest in both cases should show the mimetype, size, and md5 of each file
**Note: Don't merge this before  #342**

Add md5, mimetype, and file sizes to bag manifest

---

plugin_tests/import_test.py
server/rest/tale.py
server/tasks/import_binder.py
server/tasks/import_tale.py

Some of the routes used to create Tales were returning a Job instead of a Tale object due to fact creation was a long and convoluted task. This behavior breaks REST assumption and is difficult to handle by the UI. It affects:
* Analyze in WT
* Analyze in WT "binder flavor" (i.e. data is imported to workspace)
* Importing Tale from ZIP
All variants of `POST /tale/import` now return Tale object and do that fairly quickly, while spawning necessary long-running tasks as jobs. Note, that it means that the Tale object returned by that route is incomplete and may (or I should rather say *will*) change without any notice to the consumer.
1. Analyze in WT
1. Deploy this branch and corresponding gwvolman branch (https://github.com/whole-tale/gwvolman/pull/85)
1. Navigate to …

Create Tales upfront in POST /tale{/import}

---

server/lib/globus/globus_provider.py
server/utils.py

This PR switches Globus provider from parsing the now obsolete https://publish.globus.org/ to https://petreldata.net/mdf. ~I still hope that someday Globus' search index could be used to get all the data we need...~ Globus dataset id is derived from the resulting url and used to query Globus Search API to get all the necessary metadata.
1. Deploy
2. Try to register a couple MDF datasets (e.g. 10.18126/M2662X, 10.18126/M2301J, note that these are the ones I've used for testing, so I'll get bonus points if you can test using something else ;-) )
3. Confirm that dataset is recognized as provided by "Globus". Confirm it actually registers and is accessible from within a Tale.

Update globus provider. Fixes #338

---

plugin.cmake
plugin_tests/import_failures_test.py
plugin_tests/tale_test.py
server/models/tale.py
server/rest/tale.py
server/tasks/copy_workspace.py
server/tasks/import_binder.py
server/tasks/import_tale.py

Importing an external dataset as a "binder" or "copy-on-launch" feature, both involve file operations on Tale workspace. Currently, it is possible to trigger image build before those operations are finished. With this PR (and a corresponding https://github.com/whole-tale/gwvolman/pull/86) we prevent that from happening by setting the Tale status to `PREPARING` when the Tale is created and switching it to `READY` only after all workspace i/o is done. (Note: before that was only implemented for "copy on launch"). Additionally, whenever Tale import fails, Tale status is set to `ERROR` to indicate that Tale is incomplete (cc @bodom0015 I'm not sure how, if at all, this will affect UI...)
In short "Import as Binder" any dataset that has a modified environment. To make it easier I created …

Delay Tale operations involving workspace until it's ready

---

plugin_tests/import_test.py
server/rest/tale.py

Sets the default category to 'science' for tales that are created from datasets.
To Test:
1. Make sure you have less than 2 instances running
2. Visit https://girder.local.wholetale.org/api/v1/integration/dataone?uri=https%3A%2F%2Fsearch.dataone.org%2Fview%2Fdoi%3A10.18739%2FA2VQ2S94D&title=Fire influences on forest recovery and associated climate feedbacks in Siberian Larch Forests%2C Russia&environment=RStudio
3. Create and launch the Tale
4. Check the metadata tab for 'science'
Fixes https://github.com/whole-tale/girder_wholetale/issues/362

Set Default Category for Tale Imports

---

plugin.cmake
plugin_tests/data/zenodo_hierarchy.txt
plugin_tests/data/zenodo_lookup.txt
plugin_tests/data/zenodo_manifest.txt
plugin_tests/dataverse_test.py
plugin_tests/zenodo_test.py
server/__init__.py
server/constants.py
server/lib/__init__.py
server/lib/dataverse/provider.py
server/lib/globus/globus_provider.py
server/lib/http_provider.py
server/lib/import_providers.py
server/lib/zenodo/provider.py

This PR allows to register resources from Zenodo.
* Datasets in Zenodo have versions (revisions). Each of them has a unique DOI you can use to register it. A collection of revisions can be referenced by a single "Concept" DOI, which AFAICT points to the latest revision by default. In order to differentiate between versions, we append `_rev{}` to root folder in the WT Catalog. ConceptDOI is stored as a metadata keyword.
* Zenodo provider supports multiple targets (e.g. "zenodo.org", "sandbox.zenodo.org") which can be configured via plugin's config page. Specific target that was used to register data, is now being stored as metadata entry in the root folder. (_subProvider_)
* The fact that the folder structure in Zenodo is just a labeling, i.e. there are no actual folders you can download, …

Add Zenodo external data provider

---

server/schema/misc.py

As a convenience this adds `repository` and `repository_id` to *Tale's* `publishedInfo`. The former will match whatever is used as an argument to `PUT /tale/:id/publish?repository=...`, the latter will be repository specific identifier.
This will help to trace back to published Tales in cases when DOI resolution is not possible, e.g. sandbox Zenodo, Dev MetacatUI etc.

Include repository information in Tale's publishInfo

---

plugin.cmake
plugin_tests/oauth_test.py
server/__init__.py

Restores globus transfer token saving (in a sane way) after https://github.com/whole-tale/girder/commit/2fcdb1fb18a72907d3775eedb07ae4549546fc1a
1. Make sure you're using latest `wholetale/girder` which is `sha256:4c4a55e86186080d7dbef73dda409227e6614b4e8eb341ea5a07c9d1d2d79601`
1. Deploy, login using Globus, configure any number of external accounts via https://girder.local.wholetale.org/#ext_keys
1. Logout and login again.
1. Confirm that all the tokens you configured + Globus transfer token are still there:
```
$ docker exec -ti $(docker ps --filter=name=wt_girder -q) girder-shell
from girder.models.user import User
User().findOne({"admin": False})["otherTokens"]
```

Save globus transfer token without clobbering otherTokens. Fixes #369

---

plugin_tests/repository_test.py
server/constants.py
server/rest/repository.py
server/schema/misc.py

1. Connect "DataONE Dev" and Zenodo (sandbox) accounts
2. Hit `GET /repository` and confirm it returns:
```
[
{
"name": "DataONE Dev",
"repository": "https://dev.nceas.ucsb.edu/knb/d1/mn"
},
{
"name": "Zenodo Sandbox",
"repository": "sandbox.zenodo.org"
}
]
```

Return a "friendly" repository name in GET /repository. Fixes #374

---

plugin_tests/data/tale_import_zip.txt
plugin_tests/dataverse_test.py
plugin_tests/harvester_test.py
plugin_tests/import_failures_test.py
plugin_tests/import_test.py
plugin_tests/zenodo_test.py
server/lib/data_map.py
server/lib/import_providers.py
server/lib/zenodo/integration.py
server/lib/zenodo/provider.py
server/models/tale.py
server/rest/integration.py
server/rest/tale.py
server/tasks/import_tale.py

This PR introduces Zenodo "integration" route that allows to import published Tales.
Note: Depends on https://github.com/whole-tale/gwvolman/pull/98
1. Create and publish a Tale to sandbox.zenodo.org. Make sure it includes a) registered dataset, b) some files in the workspace.
1. Remove Tale locally.
1. Open an incognito session
1. Go to published record and follow `Run this Tale on Whole Tale by clicking here.` in the record's description.
1. You should be asked to login and after a while you should end up on dashboard's run page for freshly imported Tale
1. (optionally) Make some modification and publish the Tale again. Confirm that it created new version, rather than a new deposition.
1. Remove the Tale
1. Navigate to swagger page, use `POST /tale/import` by providing only `url` to …

Tale importing and AinWT from Zenodo

---

plugin_tests/import_test.py
server/tasks/import_binder.py

The World is full of data. Some of that data can actually be binder compatible. The way we currently register the data, often prevents us from easily creating a Tale from a binder/tale-like dataset. This PR introduces some magic to make WT a better place!
As reminder `POST /tale/import` can take a url to an external dataset. If combined with `asTale=True` this dataset ends up in a workspace directory. This PR performs some modifications to the content of the workspace, namely:
1. If the workspace contains a single directory, move all content of that directory a level up, then remove the directory
1. If the workspace contains a singe zip/tar file, unpack it, then remove the zip/tar file
Modifications are performed recursively, so if you watched too much *Inception* and try to throw at me a …

Apply some heuristics to make certain datasets look more like a binder

---

plugin_tests/dataone_register_test.py
server/lib/dataone/register.py

During data registration from DataONE, we parse the user's input to locate the identifier/doi. For example, the user can pass in `https://search-demo.dataone.org/view/urn:uuid:34d66cfa-0798-493a-b264-ebf529fb5c12`-we want to extract `urn:uuid:34d66cfa-0798-493a-b264-ebf529fb5c12`.
We hit most cases, but miss links that hit the `view` endpoint on different domains. I added a last check to see if 
To Test:
1. Try to "analyze in WT" with [this link](https://girder.local.wholetale.org/api/v1/integration/dataone?uri=https://test.arcticdata.io/view/urn:uuid:429dac8f-9153-400b-ac75-a45e4eb6085a&title=arcticdata%20R%20package%20test&api=https://cn-stage.test.dataone.org/cn/v2), coming from test.arcticdata.io
2. Note that you won't get the dataset
3. Check this branch out
4. Visit the same link
5. …

Look for view endpoint in dataone data registration

---

plugin_tests/basic_test.py
plugin_tests/tale_test.py
server/__init__.py
server/models/tale.py
server/schema/misc.py

Perform some sanity checks on Tale's `dataSet`
1. Register any dataset (e.g. 10.5065/D6862DM8), create a Tale, add "Humans and ..." folder to dataSet using Run > External Data > "+". Note your Tale's id, it will come handy in step 2.
2. Using Swagger, modify dataSet `_modelType` from folder to item. The easiest way of doing that:
`GET /tale/:id`, copy and paste to `PUT /tale/:id`, change the field manually.
3. You should get 400 error for PUT

Validate Tale's dataSet. Fixes #372

---

plugin_tests/data/tale_import_data.txt
plugin_tests/import_failures_test.py
plugin_tests/import_test.py
server/models/tale.py
server/rest/tale.py
server/tasks/import_binder.py
server/tasks/import_tale.py

* obsoletes gwvolman.import_tale - now it's done via import_binder task
* fixes mutable default argument in POST /tale/import
* adds support for import_binder on a http resources
* fix progress counter and messages
Follow all the test cases from https://github.com/whole-tale/wt-design-docs/blob/master/ISSUE_TEMPLATE/test_plan.md#analyze-in-whole-tale

Refactor Analyze in WT tasks

---

server/lib/dataone/provider.py

The coordinating-member node relations can be confusing at times. When we register data from DataONE, it's common to have the member node or the coordinating node along with the dataset identifier.
When we have the member node, we use its `object/` endpoint to access the bytes of the file. When using the coordinating node, we would use the `resolve/` endpoint to get the bytes of the file (I think resolve will redirect you to the proper member node).
The code that was doing the above runs into issues when we use any coordinating node that isn't production by tacking the `object/` endpoint on it.
Instead of worrying about whether we're getting a member node or a coordinating node, I've switched the Analyze in Whole Tale feature on the DataONE side to always send the coordinating node, …

Use Coordinating Node to Register Data

---

plugin_tests/integration_test.py
plugin_tests/zenodo_test.py
server/lib/dataone/integration.py
server/lib/dataverse/integration.py
server/lib/import_providers.py
server/lib/integration_utils.py
server/lib/zenodo/integration.py
server/lib/zenodo/provider.py

In order to prevent a situation when user creates multiple copies of a Tale by either clicking AinWT integration or Zenodo import link, import routes now check if such Tale already exists using info from `related_identifiers`.
1. Follow those links more than once:
1. [Zenodo](https://girder.local.wholetale.org/api/v1/integration/zenodo?doi=10.5281%2Fzenodo.3620778&resource_server=zenodo.org)
1. [Dataverse](https://girder.local.wholetale.org/api/v1/integration/dataverse?datasetPid=doi%3A10.7910%2FDVN%2F3MJ7IR&siteUrl=https%3A%2F%2Fdataverse.harvard.edu)
1. [DataOne](https://girder.local.wholetale.org/api/v1/integration/dataone?environment=RStudio&force=False&uri=https%3A%2F%2Fsearch.dataone.org%2Fview%2Fdoi%3A10.18739%2FA2VQ2S94D&title=Fire+influences+on+forest+recovery+and+associated+clima …

Don't recreate Tales in AinWT by default if they're already imported

---

server/lib/__init__.py

1. Register 1-2 datasets
2. Create a Tale, add data from 1.
3. Using Tale's metadata view confirm that the number of `Cites` relations matches entries in `Datasets used`

Update related ids upon dataSet change. Fixes #402

---

plugin_tests/manifest_test.py
server/lib/manifest.py

This PR removes the README.md record from the manifest. It was inconsistent with what we do for other bag-level files (run-local.sh).
To Test:
1. Check out the branch in [this](https://github.com/whole-tale/gwvolman/pull/104) gwvolman PR
1. Deploy
1. Export a Tale
1. Open metadata/manifest.json
1. Confirm you don't see the README
1. Confirm that you see the README.md file in the bag root
1. Publish to DataONE development
1. You should see the README file in the file list, and a blurb about it towards the bottom of the page
This shouldn't effect Zendo publishing in any way, but I went ahead and published to Zenodo sandox and things look fine.
This should obsolete https://github.com/whole-tale/girder_wholetale/pull/400

Remove readme from manifest

---

plugin_tests/accounts_test.py
server/lib/__init__.py
server/lib/dataone/auth.py
server/lib/dataverse/auth.py
server/lib/zenodo/auth.py
server/rest/account.py

1. Go to https://dashboard.local.wholetale.org/settings, open the Dev Console
1. Add zenodo/dataverse key that's invalid
1. Key should not be accepted, exception should be thrown in the console
1. Add a valid zenodo/dataverse key
1. Auth provider should be connected.

Validate apikeys before storing them. Fixes #404

---

plugin_tests/tale_test.py
server/lib/exporters/__init__.py
server/lib/exporters/bag.py
server/lib/exporters/native.py
server/models/tale.py
server/rest/tale.py

With this change we can keep any modifications made to Tale's runtime (memLimit, runPath etc) during publish and properly restore it back.
1. Deploy this locally.
1. Import https://sandbox.zenodo.org/record/509115, run it and prepare to be amazed.

Export final env config and restore it properly during Tale's import

---

server/models/tale.py

Tale title is not displayed properly on rebuild notifications.
Fix typo in `buildImage` in one of the field names

Fix tale title field name in buildImage

---

plugin_tests/instance_test.py
server/models/instance.py

Fixes one of the issues found during testing of `wt_versioning`. Since it went unnoticed that long, I think the only way to test it is via `girder-shell` and loading of a *Instance* object.

Force a sessionId to be stored as an ObjectId

---

server/__init__.py

It's useful since PIs of the project have a nasty habit of asking questions like: "How many users used the system in past n months?" and expecting an immediate answer. Parsing logs to find that out is tedious, so let's keep that in the db.
1. Deploy and login to girder.
1. Using swagger API, call `/user/me` and verify that `lastLogin` field is present and contains the date when you last logged in.

Track the date of the users' last login

---

server/lib/manifest.py

Fixes #416
To Test
1. Checkout
2. Export a Tale
3. Open the manifest
4. Check that the ordering has `https://w3id.org/bundle/context` at the end

Re-order the context

---

plugin_tests/tale_test.py
server/models/tale.py

Fixes #373 
Open to suggestions for wording changes in the default description.
To test:
1. Checkout
2. Go to the girder API (The dashboard provides a default Tale description too)
3. POST a new Tale (use the chunk below)
4. Make sure you see the default description
```
{
"_accessLevel": 2,
"_id": "5f839b0439895bd373eq5eed",
"_modelType": "tale",
"authors": [],
"category": "science",
"config": {},
"copyOfTale": null,
"created": "2020-10-11T23:53:40.360000+00:00",
"creatorId": "5f6e609ab2bb2d8dfe456502",
"dataSet": [],
"dataSetCitation": [],
"folderId": "5f839b0439895bd373ea5eef",
"format": 8,
"icon": "https://raw.githubusercontent.com/whole-tale/jupyter-base/master/squarelogo-greytext-orangebody-greymoons.png",
"iframe": true,
"illustration": …
```

Add default description

---

server/lib/__init__.py
server/rest/dataset.py
server/tasks/register_dataset.py

This PR converts the dataset registration process into a job, which in turn allows for nice notifications in the dashboard (fixes https://github.com/whole-tale/ngx-dashboard/issues/43).
1. Deploy, register LIGO Tale
1. Create a new Tale
1. Navigate to View Tale / Files / External Data
1. Click on (+) / Web (DOI or URL)
1. Enter `doi:10.5065/D6862DM8`, click Search, then Register
- Notification should pop up
1. (optionally) Follow the AinWT flow and verify that there's no additional registration notification, only a single one encompassing the entire AinWT process.
1. Navigate to https://girder.local.wholetale.org/api/v1/integration/dataverse?datasetPid=doi%3A10.7910%2FDVN%2F3MJ7IR&siteUrl=https%3A%2F%2Fdataverse.harvard.edu

Convert registration process to a job. Fixes #306

---

server/lib/manifest.py
server/models/tale.py

This ensures that a Tale always has `imageInfo` property. Fixes https://github.com/whole-tale/gwvolman/issues/116

Add a stub for imageInfo during Tale creation

---

plugin.cmake
plugin_tests/git_test.py
requirements.txt
server/constants.py
server/models/tale.py
server/rest/tale.py
server/tasks/import_git_repo.py

Allows to either import a git repo to a workspace of an existing Tale, or import a remote git repo as a Tale (AinWT flow).
new API:
- `PUT /tale/:id/git` ( for *"Connect to Git repository..."*)
- `POST /tale/import?git=True&url=<git_repo>` ( for *Create New... > Create Tale from Git Repository*)
this case follow the existing Analyze in WT flow. The only difference is the new `git` boolean parameter in the request that triggers a job which interprets `url` as a git repository url.
1. Checkout and run this branch locally
2. Ensure dependencies are installed: `docker exec -ti $(docker ps --filter=name=wt_girder -q) girder-install plugin plugins/wholetale`
3. t.b.a

Git integration

---

server/schema/misc.py

Adds:
* "buildpack" - we have been using it for a long time already
* "repo2docker_version" - it will allow to build tales with a specific version of r2d in the (not so distant) future

Update ContainerConfig schema

---

plugin_tests/manifest_test.py
server/lib/manifest_parser.py
server/models/tale.py
server/tasks/import_tale.py
setup.cfg

This is basically a no-op PR that only refactors code related to parsing `manifest.json` and `enviroment.json` into a Tale. New methods that were moved to `lib.manifest_parser` will come in handy for restoring Tales from previous versions.
1. Create and publish a Tale to Zenodo (preferably with complicated `dataSet` i.e. folder, file, various providers)
2. Remove the Tale (potentially clean girder's db to remove all trace of registered data etc.)
3. Import the Tale
or...
1. Inspect the code since the aforementioned test scenario is already covered by test suite.

Refactor manifest-to-tale parsing

---

plugin_tests/import_test.py
plugin_tests/tale_test.py
server/constants.py
server/models/tale.py
server/rest/instance.py
server/rest/tale.py
server/schema/tale.py

This PR removes support for two unused "features" from Tale model: "old" data folder and narrative folder. It's a first step for a new and *better* handling of auxiliary folders. The only remaining folder is `workspace` but I plan to move it where it belongs, i.e. `wt_home_dirs` plugin.

Drop obsolete folderId and narrative from Tales

---

plugin_tests/dataverse_test.py
plugin_tests/manifest_test.py
server/lib/manifest.py
server/lib/manifest_parser.py
server/rest/tale.py

This PR introduces a few changes to manifest machinery:
1. Girder UUIDs are now stored in the individual objects in the `aggregates` section under `schema:identifier` field
2. Folder from `dataSet` are only expanded into individual items during manifest creation if `expand_folders` is set and their URI is not well defined (e.g. you cannot request to download a specific folder from DV dataset). Previous it behaved differently:
1. HTTP folders were *always* expanded regardless `expand_folders` value.
2. Globus folders were expanded if `expand_folders` were True. This no longer a case, since they have a valid URI.
3. Restoration of a `dataSet` from manifest now uses the new `schema:identifier` and only defaults to the "old ways" if it's not present. This will allow to restore a Tale from a …

Updates to manifest format

---

plugin_tests/tale_test.py
server/lib/exporters/__init__.py
server/lib/exporters/bag.py
server/lib/exporters/native.py
server/lib/manifest.py
server/models/tale.py

Extracting serialization into separate methods, allows to easily reuse them elsewhere. One particular place I have in mind is using Tale -> Manifest -> Tale cycle for easy in-between-versions comparison of Tale objects, but that's a separate PR (though partially hinted in tests here)

Refactor manifest/environment serialization

---

plugin_tests/dataverse_test.py
plugin_tests/import_test.py
plugin_tests/manifest_test.py
plugin_tests/zenodo_test.py
server/lib/__init__.py
server/lib/exporters/__init__.py
server/lib/exporters/bag.py
server/lib/exporters/native.py
server/lib/manifest.py
server/lib/manifest_parser.py
server/models/tale.py
server/rest/tale.py
server/tasks/import_tale.py

Implementation of https://github.com/whole-tale/serialization-format/pull/2 for testing. I refactor `ManifestParser` a bit to be more flexible and perform autoupdate of schema in case of old schema version.
Needs https://github.com/whole-tale/wt_versioning/pull/19 to work properly.

Update manifest routine wrt a new schema

---

plugin_tests/tale_test.py
server/lib/exporters/__init__.py
server/lib/exporters/bag.py
server/lib/exporters/native.py
server/lib/manifest.py
server/rest/tale.py

This PR converts tale exporters to work solely on information contained in `manifest.json`, `environment.json` (or they "live" equivalents from `Manifest` class) and a physical path to workspace that we bundle. This approach avoids some pitfalls with circular dependencies between Version, Tale, and Manifest and makes what we are exporting more clear.
1. Exports some Tales and see that nothing is changed.
2. (optional) test with https://github.com/whole-tale/wt_versioning/pull/21 and e.g. check that version is created only once and it's actually included in the bag.

Decouple Tale exporting from girder models

---

server/lib/exporters/bag.py

Fixing a typo that was introduced in https://github.com/whole-tale/girder_wholetale/pull/446 and broke `fetch.txt` format.

fix: bagit was using wrong keyword for filename

---

plugin_tests/git_test.py
plugin_tests/import_test.py
plugin_tests/instance_test.py
plugin_tests/tale_test.py
plugin_tests/tests_helpers.py
server/__init__.py
server/models/instance.py
server/models/tale.py
server/rest/tale.py
server/tasks/import_binder.py
server/tasks/import_git_repo.py
server/tasks/import_tale.py
server/utils.py

**Problem**:
Under a number of scenarios, the dashboard must be manually refreshed to reflect changes to underlying data, particularly when a tale is shared with another user (see https://github.com/whole-tale/ngx-dashboard/issues/121).
**Approach:**
This PR adds support for sending specific Girder events to users with access to a Tale for the following:
* Tale is created (`wt_tale_created`), updated (`wt_tale_updated`),  (`wt_tale_removed`)
* Tale is shared (`wt_tale_shared`) or unshared with a user (`wt_tale_unshared`)
* Import is started (`wt_import_started`), completed (`wt_import_completed`) or failed (`wt_import_failed`)
* Instance is started (`wt_instance_launching`), running (`wt_instance_running`), or in error state (`wt_instance_error`)
This PR adds support for sending specific …

Add notifications for shared events

---

plugin_tests/basic_test.py
plugin_tests/instance_test.py
server/__init__.py
server/rest/instance.py

See https://github.com/whole-tale/deploy-dev/pull/44 for test and https://github.com/whole-tale/whole-tale/issues/94 for problem description.
This PR adds the `/instance/authorize` and `/user/sign_in` endpoints intended to work with Traefik forward authentication to determine whether a user has access to an instance by hostname.

Add endpoint to check whether user is authorized to access an instance

---

plugin_tests/import_failures_test.py
server/rest/tale.py
server/tasks/copy_workspace.py

* operate on Tale objects rather than paths
* emit 'wholetale.tale.copied' for other plugins to consume
1. Depends on https://github.com/whole-tale/girder/pull/10
1. Register a Ligo Tale
2. Copy and launch. Verify it succeeds.

Updates to copy_workspace job

---

server/utils.py

Reduces event notification expiration time for events that do not require user acknowledgment to 5s.  This should resolve the problem identified in https://github.com/whole-tale/ngx-dashboard/pull/139#issuecomment-801423095.
To test:
* As user 1, create and share tale with user 2 with both users actively logged in
* User 1 and user 2 select metadata page in edit mode
* User 1 edits tale metadata and saves, user 2 confirms sync modal appears and selects either yes or no
* Wait 30s
* Sync modal should not reappear

Decrease notification expiration time

---

server/models/instance.py

**Problem**:
The `_wait_for_server` function used to determine whether a tale is up and routable no longer works due to recent forward authentication changes.  
**Approach**:
Update `_wait_for_server` to pass a token for the instance creator and add the `girderToken` cookie to the request. It seemed easier to do this with `requests`.
**Test case**:
* Requires real DNS (i.e., not local)
* Start an instance and watch the girder logs for `Booting server...` messages
* Confirm that these end when the instance service is ready and that the tale is accessible via the UI

Add token cookie to _wait_for_server request

---

server/rest/dataset.py

`POST /dataset` was leaking too much info. Fixed by applying a proper model filtering.

Filter dataset registration job in POST /dataset

---

server/rest/tale.py

Update tale's icon field whenever imageId changes. Fixes #473

---

server/rest/tale.py
server/tasks/import_binder.py

Fixes https://github.com/whole-tale/girder_wholetale/issues/476 (see test case in that issue).
This PR adds a `wt_progress` notification for the `import_binder` job.

Add progress notification to import_binder job

---

plugin.cmake
plugin_tests/globus_test.py
server/lib/globus/globus_provider.py

I think this is a third consecutive release where we discover that registering MDF resources is broken. That tells me two things:
1. Our testing plan is really good (thanks @bodom0015)
2. Nobody is using this in production.
Per 2. if that ever happens again (my bet: during v1.1 release) my next PR with a "fix" will simply drop MDF support.
1. Follow the testing plan concerning registration of Globus resources.

Update MDF provider. Fixes #466

---

plugin_tests/git_test.py
plugin_tests/import_test.py
plugin_tests/instance_test.py
plugin_tests/publish_test.py
plugin_tests/repository_test.py
server/constants.py
server/lib/__init__.py

Note that except for the change to `server/lib/__init__.py` this PR merely changes the defaults. It can be also done directly via configuring a running instance of Girder.

Convert DataONE auth to api_key provider

---

plugin_tests/git_test.py
plugin_tests/import_failures_test.py
plugin_tests/import_test.py
server/tasks/copy_workspace.py
server/tasks/import_binder.py
server/tasks/import_git_repo.py
server/tasks/import_tale.py

As a result there should be less spurious notifications sent to the users, which should make whole-tale/ngx-dashboard#181 less noticeable. Also updating a single field instead of entire documents seems like a right thing to do in case of status updates.
It's basically a noop PR. Not sure how to test it properly... Do some imports and confirm everything still works?

Decrease the amount of Tale().updateTale calls during import

---

plugin_tests/accounts_test.py
server/lib/dataone/auth.py

This should at least prevent a situation when we store an empty string due to some magical circumstances.

Verify that D1 token is a valid JWT

---

circle.yml
plugin_tests/instance_test.py
plugin_tests/notification_test.py
server/__init__.py
server/models/tale.py
server/utils.py

If job ended up in a success, and had a correct number of steps defined by progressTotal, it was actually impossible to issue final `wt_progress` message if both job status and progress were updated in the same step.
NOTE I think that logic is still wrong in case we have an intermediate job finishing and the subsequent sub-job has one step...
Requires: https://github.com/whole-tale/girder/pull/13 or prebuilt image: `wholetale/girder:event`

Correctly update wt_progress for last notification

---

server/schema/tale.py

Tale `status` field is not defined in the Swagger spec, though it is provided in the example value for a Tale. 
Add a definition for the `status` property to the Tale schema. We should ensure that the attributes required by any clients (UI + worker, at the very least) are defined in the schema in case we ever need to re-generate the code (e.g. when switching frameworks, writing a new client, etc)
Note that even with this change, the Swagger spec produced by `/api/v1/describe` is not a truly "valid" Swagger spec... see https://github.com/whole-tale/girder_wholetale/issues/358 for more details on what would likely be a more controversial set of changes
1. Checkout and run this branch locally
2. View https://girder.local.wholetale.org/api/v1/describe
* You should see the full Swagger spec …

Add Tale status to swagger spec/schema

---

plugin_tests/zenodo_test.py
server/models/tale.py

POST /tale/import for zipfiles was relying on WTHomeFSAssetstore which no longer exists...

use tempdir on default assetstore during import zip

---

plugin_tests/data/dataone_lookup.txt
plugin_tests/data/dataverse_lookup.txt
plugin_tests/data/dataverse_single.txt
plugin_tests/dataverse_test.py
plugin_tests/harvester_test.py
server/lib/dataverse/provider.py
server/lib/http_provider.py
server/lib/resolvers.py

Multiple issue related to registering data from DV crept up. Mostly due to the fact that we are using "prerecorded" request responses in our test suite. Some of the issues can be solved on our end:
1. Urlib requests to DV result in 403 for some reason. Solution: switch to requests
2. DV started to encode filenames in `Content-Disposition` headers, but they're doing it in two different ways (see https://github.com/IQSS/dataverse/issues/7962). Solution: decode...
Remaining issue causing breakage is isolated to Harvard's DV instance. Namely, search with query parameter `entityId` is not working there properly. I filed a ticket about it but unfortunately it's on a private tracker.

Dataverse provider updates

---

plugin_tests/zenodo_test.py
requirements-dev.txt
requirements.txt
server/lib/dataone/integration.py
server/lib/dataverse/integration.py
server/lib/zenodo/__init__.py
server/lib/zenodo/integration.py
server/lib/zenodo/provider.py
server/tasks/import_binder.py

Prior to this PR we could only import Tales from Zenodo in AinWT workflow. This PR adds the missing component that triggers `import_binder` for non-tale datasets similarly to DV and DataONE integrations.

Enable AinWT for non-tale datasets from Zenodo

---

plugin_tests/data/tale_import_data.txt
plugin_tests/dataverse_test.py
plugin_tests/import_test.py
plugin_tests/tale_test.py
server/lib/dataverse/integration.py
server/lib/dataverse/provider.py
server/lib/import_providers.py
server/rest/tale.py

Create nicer looking (metadata-wise) tales when importing from Dataverse.
1. Import random AJPS supplement from dataverse, e.g. https://girder.local.wholetale.org/api/v1/integration/dataverse?siteUrl=https%3A%2F%2Fdataverse.harvard.edu%2F&datasetPid=doi%3A10.7910%2FDVN%2F26721&fullDataset=true&force=false
2. Verify that metadata (title, author, description) matches the original dataset's metadata

During AinWT prepopulate Tale fields based on Dataverse metadata

---

server/__init__.py

Required for properly handling the case when endpoint is accessed via `&token`.

Set the cookie in case user was authenticated but session does not have it

---

server/__init__.py

To work properly it also requires `secure` attribute (preferably set to True). It's already being handled by girder proper. Just do:
```
PUT /system/setting?key=core.secure_cookie&value=true
```

Set 'samesite' to None for sign_in cookies

---

circle.yml
plugin_tests/dataverse_test.py
plugin_tests/manifest_test.py
plugin_tests/tale_test.py
server/lib/exporters/__init__.py
server/lib/exporters/bag.py
server/lib/exporters/native.py
server/lib/manifest.py
server/rest/tale.py

Fixes https://github.com/whole-tale/whole-tale/issues/90
This PR:
* Updates `manifest.py` to include recorded run information and files if one or more runs are present for a version
* Updates exported tales to include updated manifest.json and run files in payload
To test:
* Create a new tale with two entrypoint scripts that create output files
* Execute a recorded run for each entrypoint
* Export tale/version associated with the run
* Confirm that the `manifest.json` includes information for both runs 
* Confirm that payload includes files from both runs

Export recorded runs

---

server/lib/dataone/auth.py

Trying to access registered DataONE resource with DMS resulted in:
```
Traceback (most recent call last):
File "/girder/girder/api/rest.py", line 630, in endpointDecorator
val = fun(self, path, params)
File "/girder/girder/api/rest.py", line 1230, in POST
return self.handleRoute(method, path, params)
File "/girder/girder/api/rest.py", line 970, in handleRoute
val = handler(**kwargs)
File "/girder/girder/api/access.py", line 63, in wrapped
return fun(*args, **kwargs)
File "/girder/plugins/wt_data_manager/server/resources/lock.py", line 101, in acquireLock
return self.model('lock', 'wt_data_manager').acquireLock(user, sessionId, itemId, ownerId)
File "/girder/plugins/wt_data_manager/server/models/lock.py", line 83, in acquireLock
events.trigger('dm.itemLocked',
File …
```

[DataONE] add missing headers prop to DataONEVerificator

---

server/lib/exporters/__init__.py
server/lib/exporters/bag.py

This PR adds sha1 support in exported bags. sha1 is a possible algorithm used by DataONE for registered datasets (see https://github.com/whole-tale/girder_wholetale/pull/524).

Add sha1 support to bag export

---

plugin_tests/constants_test.py
plugin_tests/dataone_register_test.py
plugin_tests/publish_test.py
plugin_tests/repository_test.py
server/constants.py
server/lib/__init__.py
server/lib/dataone/__init__.py
server/lib/dataone/fakeoauth.py

~~D1 has renamed `cn-stage-2.test.dataone.org` to `cn-sandbox.test.dataone.org`. The hostname is redirecting and the cert is only valid on cn-sandbox.test.dataone.org.~~
See comment below. D1 has consolidated cn-stage-2 and cn-stage, of which dev.nceas.ucsb.edu is now a member node.
**To Test:**
* Requires https://github.com/whole-tale/gwvolman/pull/168
* Create a simple tale
* Go to Settings, connect cn-stage.test.dataone.org
* Publish your tale to https://dev.nceas.ucsb.edu/
* Confirm that the resulting published dataset looks sensible
* For grins, change something and publish again

Change staging cn to cn-stage

---

plugin_tests/integration_test.py
server/lib/dataone/integration.py
server/lib/dataone/provider.py

Reverting my invalid change for non-tale case.  D1 integration requires that only the fields that are set on integration request are included on redirect.
**Test case**
* Import dataset as READ-ONLY https://girder.local.wholetale.org/api/v1/integration/dataone?uri=https%3A%2F%2Fsearch.dataone.org%2Fview%2Fdoi%3A10.18739%2FA2VQ2S94D&title=Fire%20influences%20on%20forest%20recovery%20and%20associated%20climate%20feedbacks%20in%20Siberian%20Larch%20Forests%2C%20Russia&environment=RStudio
* Make sure tale is created, data is registered and present. Optionally run tale.
* Import tale https://girder.local.wholetale.org/api/v1/integration/dataone?uri=https://dev.nceas.ucsb.edu/view/urn:uuid:dd6039b1-caa4-492f-968f-1562cc93a363&title=WT%20Recorded%20Run%20Test%20(sans%20DERIVA%20and%20Globus)&envi …

D1 integration redirect fix

---

server/__init__.py
server/lib/deriva/auth.py

Fixes #534 (for now...). Avoids doubling deriva scope in oauth requests. I'll note that a better solution would be to use `set()` for scopes in oauth provider, but I don't want to mess with girder proper for now.
1. See #534 
2. Alternatively:
```
$ docker exec -ti -u root $(docker ps --filter=name=girder -q) gosu girder:girder girder-shell
> from girder.plugins.oauth.providers.globus import Globus
> Globus._AUTH_SCOPES
```
verify that there are no duplicates.

Only add new globus scopes during plugin load

---

server/__init__.py

Other provider don't bundle `other_tokens`.

Don't assume we used globus for login

---

server/lib/dataverse/provider.py

Fixes issue identified during live demo!
1. Navigate to https://wholetale.readthedocs.io/en/latest/ainwt.html
2. Select: Dataverse, https://dataverse.harvard.edu/, doi:10.7910/DVN/NYPOQD
3. Click Launch Tale
4. Tale should import properly.

grab ORCID from DV meta more defensively

---

plugin_tests/harvester_test.py
server/lib/dataone/provider.py
server/lib/dataverse/provider.py
server/lib/globus/globus_provider.py
server/lib/zenodo/provider.py
server/rest/dataset.py

For Zenodo, Dataverse, DataONE and Globus providers this PR annotates registered data with a) location of a file/folder relative to the original dataset root b) identifier of root dataset (in case there's a specific file/folder identifier it's added as `directIdentifer` to metadata)
Currently this information is derived ad hoc from the structure of WholeTale Catalog using a lot of implicit assumptions regarding how registering works for a given provider. With this PR it's going to be easy to export / import external data regardless of its location in girder.
1. Register some data. I used:
1. https://zenodo.org/record/3463499 (nested zenodo)
2. doi:10.7910/DVN/5WTSUZ (nested DV)
3. https://search.dataone.org/view/urn:uuid:6f5533ab-6508-4ac7-82a3-1df88ed4580e
4. doi:10.18126/M2301J (globus) …

Annotate registered data with location labels

---

plugin_tests/bdbag_test.py
plugin_tests/dataverse_test.py
plugin_tests/manifest_test.py
plugin_tests/tale_test.py
server/lib/exporters/bag.py
server/lib/manifest.py
server/lib/manifest_parser.py

**Problems addressed**
* The registry requires authentication so it isn't possible for anyone to access the built image for a tale 
* When publishing or exporting a tale, the image must be built locally with repo2docker, which results in a different image 
* Third-party integrations (e.g., CORE2) can't fetch the image for archiving purposes
**Approach**
* https://github.com/whole-tale/deploy-dev/pull/52/ adds a new public read-only Docker registry at `images.local.wholetale.org` making it possible to pull any built image without authenticating.  Since both `registry` and `images` share the same filesystem, any image can be pulled publicly.
* Adds the public image URL to the manifest on export and publish, handles import (assumes image is present in our registry)
* Updates logic for …

Expose image on export and publish

---

server/__init__.py

Fixes (for now) https://github.com/whole-tale/girder_wholetale/issues/534
**Problem**
ORCID limits the size of the `state` param to 2000 characters, otherwise returning 500.   This happens on *.local now. 
**Approach**
Removed the unused scope to reduce state param size
**Test**
* Login to https://dashboard.local.wholetale.org via ORCID
* Confirm login is OK.

Remove unused Globus scope to overcome ORCID 500

---

server/rest/tale.py

**Problem**
When copying a tale (or copy-on-launch), information about the built image isn't currently included.
**Approach**
Copy the tale imageInfo excluding jobId, since it may be owned by someone else (copy on launch).
**Testing**
* Create and run a tale, note the imageInfo
* Duplicate the tale, note the imageInfo is present except jobId

feat: Include imageInfo during tale copy

---

plugin.yml
requirements.txt
server/lib/manifest.py

Turns out we were ignoring `versionId` in manifest generation, which resulted in a) wrong metadata (current instead of version specific) b) wrong files in workspace (current instead of version specific). Sadly this was affecting functionalities like export and copyTale...
1. Depends on https://github.com/whole-tale/wt_versioning/pull/47
2. Create a Tale, upload something to workspace.
3. Create a version.
4. Modify Tale's metadata (title, keywords, authors, or build it to get imageInfo) and workspace.
5. Save a version. 
6. Export the first version. Confirm that manifest.json contains proper metadata. Confirm that workspace contains proper files
7. Repeat 6. but copy the Tale from the first version instead, using "shallow=True".

fix: respect exisiting version during manifest generation

---

plugin_tests/bdbag_test.py
plugin_tests/dataverse_test.py
plugin_tests/import_test.py
plugin_tests/manifest_test.py
plugin_tests/publish_test.py
plugin_tests/tale_test.py
requirements.txt
server/lib/dataverse/provider.py
server/lib/manifest.py

During manifest creation compute `imageInfo` tag/image name using the state of workspace, rather than whatever is dangling off the Tale object.

fix: compute imageInfo dynamically based on workspace

---

plugin_tests/instance_test.py
server/__init__.py
server/constants.py
server/models/instance.py
server/rest/instance.py

Allow to fetch instance logs via exposing `service.logs`. Custom http server to do that is available from here: https://github.com/whole-tale/instance_logger
1. Modify your local deploy-dev:
```diff
diff --git a/docker-stack.yml b/docker-stack.yml
index 9960f28..5dd2425 100644
--- a/docker-stack.yml
+++ b/docker-stack.yml
@@ -72,6 +72,17 @@ services:
- "traefik.http.middlewares.girder.forwardauth.address=http://girder:8080/api/v1/instance/authorize/"
- "traefik.http.middlewares.girder.forwardauth.trustforwardheader=true"
+  logger:
+    image: wholetale/instance_logger:latest
+    networks:
+      - celery
+    volumes:
+      - /var/run/docker.sock:/var/run/docker.sock:ro
+    deploy:
+      replicas: 1
+      labels:
+        - "traefik.enable=false"
+
redis:
image: redis:4-stretch …
```

Expose instance stdout/err via GET /instance/:id/logs

---

server/__init__.py

Only update notification in `updateNotification` if it exists. Fixes #559

fix: don't update missing notification

---

server/models/instance.py

As reported by @craig-willis, there's a peculiar issue where Xpra based instances run successfully but iframe in the Interactive view doesn't show anything until you hard refresh the dashboard. It's caused by the fact that our current "health" check only looks for 200 status code, which might happen way before software inside the container actually initiliazes
Apart from checking the error code we can check if GET instance_url returns any data.
1. Deploy on .stage (already did that)
2. Run any STATA (desktop) tale and confirm that Xpra comes up without refresh.

Wait for instance to return some content before assuming it works

---

plugin.cmake
plugin_tests/bdbag_test.py
plugin_tests/export_test.py
plugin_tests/tale_test.py
server/lib/exporters/bag.py

During export check if image exists in the repository. If not, add blurb about how to build it to `run-local.sh`.
1. Create a Tale
2. Export it
3. Confirm build blurb is in `run-local.sh`
4. Build Tale
5. Export it
6. Confirm build blurb is not in `run-local.sh`
You'll need to add:
```
@@ -59,6 +59,8 @@ services:
- "GOSU_CHOWN=/tmp/data"
- DATAONE_URL=https://cn-stage-2.test.dataone.org/cn
- HOSTDIR=/
+    extra_hosts:
+      - "images.local.wholetale.org:host-gateway"
deploy:
replicas: 1
labels:
```
to `docker-stack.yml` in deploy-dev.

Add info how to build image if it's not in registry. Fixes #566

---

web_client/main.js
web_client/stylesheets/collectionsView.styl
web_client/templates/collectionsView.pug
web_client/views/CollectionsView.js

On a deployment where WT is not front and center this will allow to avoid confusion while looking at available datasets.
Use native `filterFunc` to filter out collections starting with "WholeTale"
1. Deploy this, create a tale and register random data from an external repository (to populate WT collections).
2. Navigate to https://girder.local.wholetale.org/#collections
3. View should be empty
4. Toggle the switch.
5. View should contain WholeTale collections

Add a toggle to filter WT specific collections in Collections View

---

plugin_tests/basic_test.py
plugin_tests/instance_test.py
server/__init__.py
server/rest/instance.py

**Problem**
The current forward auth implementation is limited to instances. For the HTMDEC project, we want to be able to deploy a separate service (in this case documentation) and use Girder for authorization.
**Approach**
Move the `/authorize` endpoint to the `user` and add a flag to determine whether to check for instance access. If not an instance, 
**To test**
* clone https://github.com/htmdec/htmdec.github.io unde
* Add the docs service (below) to your `docker-stack.yml` and update
* In a private session, go to https://docs.local.wholetale.org/
* Confirm that you are prompted to sign in. 
* Sign in, confirm that you see the "Welcome to nginx" page
* Go to https://dashboard.local.wholetale.org
* Start and instance and copy the instance URL
* In a new private session, try to access …

Enable authorization on arbitrary services 

---

circle.yml
plugin_tests/basic_test.py
plugin_tests/instance_test.py
server/__init__.py
server/models/instance.py
server/schema/misc.py

This method was used by `girderfs:LocalGirderFS` back in the day, but that hasn't been the case for a very long time. I've re-purposed it to work with https://github.com/data-exp-lab/girderfs_passthrough

Re-purpose GET /folder/:id/listing for passthrough fs

---

server/models/instance.py

If Instance fails during image build, `containerInfo` is not there yet on instance. As result it fails during remove Instance step with:
```
2023-05-23 17:50:24,591] ERROR: 500 Error    
Traceback (most recent call last):    
File "/girder/girder/api/rest.py", line 630, in endpointDecorator    
val = fun(self, path, params)    
File "/girder/girder/api/rest.py", line 1212, in DELETE    
return self.handleRoute('DELETE', path, params)    
File "/girder/girder/api/rest.py", line 970, in handleRoute    
val = handler(**kwargs)    
File "/girder/girder/api/access.py", line 63, in wrapped    
return fun(*args, **kwargs)    
File "/girder/girder/api/describe.py", line 709, in wrapped    
return fun(*args, **kwargs)    
File "/girder/plugins/wholetale/server/rest/instance.py", line 173, in …
```

Do not fail instance remove if volume doesn't exist
