whole-tale/girder_wholetale

plugin_tests/basic_test.py, server/__init__.py
This adds new endpoint `GET /resource` that will allow to get a list of objects using a list of ids.
=> Add a resource for getting a list of items and folders

circle.yml, plugin_tests/dataone_test.py, server/dataone_register.py, server/rest/harvester.py, server/rest/repository.py
Needs tests. Uses Py3 only features (blocked by migrating to py3 for deployment)
=> Add support for plain HTTP files as data sources. Fixes #22

plugin_tests/recipe_test.py, server/models/recipe.py, server/rest/recipe.py
=> Add access control for recipe resource

plugin_tests/image_test.py, plugin_tests/tests_helpers.py, server/models/image.py, server/rest/image.py, server/rest/recipe.py
=> Add access control for the image resource

server/dataone_register.py
Prior to this fix, looking up the package PID for a metadata PID that is a member of multiple resource maps (a common thing) failed because the logic wasn't implemented. I've implemented that logic here.
I haven't run the tests because I wasn't quite sure how to run just the dataone tests and didn't want to try to set up the full test suite that's run on Circle/Travis. I did do some manual testing though.
=> Fix a limitation (bug) in dataone_register

plugin_tests/dataone_test.py, server/dataone_register.py, server/rest/repository.py
This commit has the changes necessary to list the contents of a DataONE package.
=> Add an Endpoint to List DataONE Package Contents

plugin_tests/tale_test.py, server/models/tale.py, server/rest/tale.py
=> Add access control lists for Tale resource

README.rst
Update the readme to include some information on installing & configuring the plugin
=> Update the Readme

server/dataone_register.py, server/rest/dataset.py, server/rest/harvester.py
I was doing some UI testing and noticed these changes didn't make it in.
Adds a url parameter to `importData`, which is responsible for package registration.
=> Support Registration from any Member Node

plugin_tests/dataone_register_test.py, plugin_tests/harvester_test.py, plugin_tests/instance_test.py, plugin_tests/recipe_test.py, plugin_tests/tale_test.py, plugin_tests/tests_helpers.py, server/constants.py, server/models/tale.py, server/rest/instance.py, server/rest/tale.py
This PR:
* fixes a couple of bugs and leftovers from PR #98 
* updates test to work with new Tale behavior
=> Update test suite for PR#98

plugin_tests/tale_test.py, server/models/tale.py, server/rest/tale.py, server/schema/tale.py
`data` is reserved keyword in EmberJS
=> Use 'involatileData' instead of 'data'

plugin_tests/instance_test.py, server/__init__.py, server/constants.py, server/models/instance.py, server/rest/instance.py, web_client/InstanceStatus.js, web_client/collections/FrontendCollection.js, web_client/collections/InstanceCollection.js, web_client/routes.js, web_client/templates/configView.pug, web_client/views/ConfigView.js, web_client/views/HierarchyWidget.js, web_client/views/InstanceListWidget.js, web_client/views/widgets/FrontendSelectorWidget.js
=> Allow to limit the number of concurrently running Instances per user

server/dataone_package.py, server/dataone_upload.py
Adding some debug statements to debug an issue with local files
=> Add Debug Statements

server/dataone_upload.py
Pull the user agent of the the header and pass it as a kwarg to `create_client`
=> Pull User Agent Out of Header

server/dataone_upload.py
The `Example Tale using R` tale is breaking publishing. I'm adding some statements around the area of trouble to find out why.
=> Add Debugger Statements for Tale Troubleshooting

server/dataone_upload.py
Removed the user from the signature since force=True, got rid of a lingering debug statement, and fixed the user in the EML document.
=> Add user to resource request

circle.yml, plugin_tests/image_test.py, plugin_tests/instance_test.py, plugin_tests/tale_test.py, server/__init__.py, server/constants.py, server/models/instance.py, server/models/tale.py, server/rest/instance.py, server/rest/tale.py, server/schema/tale.py, web_client/InstanceStatus.js, web_client/collections/FrontendCollection.js, web_client/collections/InstanceCollection.js, web_client/routes.js, web_client/templates/configView.pug, web_client/views/ConfigView.js, web_client/views/HierarchyWidget.js, web_client/views/InstanceListWidget.js, web_client/views/widgets/FrontendSelectorWidget.js
This PR cherrypicks:
* https://github.com/whole-tale/girder_wholetale/pull/124
* https://github.com/whole-tale/girder_wholetale/pull/127
* https://github.com/whole-tale/girder_wholetale/pull/131
for a bugfix release.
=> Porting bug fixes to stable for micro release

server/models/instance.py
This required by https://github.com/whole-tale/gwvolman/pull/30
=> Store sessionId in the instance model.

server/lib/data_map.py
Addresses https://github.com/whole-tale/dashboard/pull/296 server side
=> Ensure that optional parameters in DataMap are REALLY optional

plugin.cmake, plugin_tests/data/DataONE_register_nested.txt, plugin_tests/dataone_register_test.py, server/lib/dataone/provider.py
`_listRecursive` call in nested DataONE pkg registration was totally off.
=> Use correct signature of _listRecursive in nested packages. Fixes #198

plugin.yml, server/lib/globus/globus_provider.py
Update dependencies to reflect https://github.com/whole-tale/girder_wt_data_manager/pull/34
=> Switch to using globus_handler plugin

server/schema/tale.py
See #215 for extensive discussion about this change.
=> Allow Tale's description to be null. Fixes #215

server/lib/dataverse/provider.py
Currently we use `wholetale.dataverse_url` to fetch either json file pointing to all public dataverse installations or point to a specific single Dataverse instance. In both cases http connection must succeed or else we just completely disable Dataverse registration support.
With this PR, we fallback to `wholetale.dataverse_extra_hosts` if anything unpredictable happens with http request.
1. Set `wholetale.dataverse_url` to random url that will return error (https://definitely.invalid.url.com)
1. Set `wholetale.dataverse_extra_hosts` to `["https://dataverse.harvard.edu"]`
1. Try GET /resource/lookup with `["doi:10.7910/DVN/R3GZZW"]`
=> Respect dataverse_extra_hosts if quering dataverse_url fails. Fixes #222

plugin_tests/tale_test.py, server/rest/tale.py
1. Create a Tale.
1. Confirm that a folder `/collection/Whole Tale Workspaces/Whole Tale Workspaces/<taleId>` exists.
1. Delete the Tale.
1. Confirm that the folder `/collection/Whole Tale Workspaces/Whole Tale Workspaces/<taleId>` doesn't exist.
=> Remove workspace when Tale is deleted. Fixes #229

plugin_tests/image_test.py, server/rest/image.py
This simplifies search images method and finally implements searching by tag. It also allows to combine various filters, i.e. search simultaneously by text and tag.
=> Allow to filter images by tag

server/lib/resolvers.py
This PR introduces a slightly more accurate check for urls that might contain a resolvable DOI.
=> Use a better regex for detecting DOIs in the resolver. Fixes #286

plugin_tests/tale_test.py, server/rest/image.py
Current default (`lowerName`) doesn't even exist in Image model. With this PR Images are sorted by `name` by default.
=> Sort images by name by default

server/lib/exporters/bag.py
See also  https://github.com/whole-tale/repo2docker_wholetale/pull/1. This is intended to fix https://github.com/whole-tale/whole-tale/issues/65.
=> Use bdbag installed in the repo2docker_wholetale image

server/lib/exporters/__init__.py
Fixes issue #344 
2. Export a Tale to a zip
3. Make sure that the README accurately reflects the changes made here
=> Add some information about the zip archive

plugin_tests/instance_test.py, server/models/instance.py
Whenever something wrong happens in jobs related to spawning instance, it is not reflected in the instance status. It results in an infinite spinner on the instance run/launch button.
Every task related to Instance spawning now carries `instance_id` as an attribute. Instance status is updated via event handler listening to a job updates.
1. In your `deploy-dev` root directory run `echo "/bin/false" > ligo_tale/postBuild`
2. Deploy this branch, run `register_ligo.py`
3. In dashboard, launch your copy of the Ligo Tale.
4. After a while, Image build should fail, and the button with a spinner should be replaced by a red `stop` button that will allow you to remove the instance.
=> Update Instance status to ERROR if image build fails during spawn. Fixes #349

server/lib/exporters/bag.py
Added missing bits required to run a Tale locally.
=> Fix 'run-local.sh' instruction in exported Tale

server/constants.py, server/models/instance.py
This should help to filter Instances that are "not yet dead" as per https://github.com/whole-tale/dashboard/pull/550#issuecomment-539655283
=> Add InstanceStatus.DELETING to indicate removal process

server/models/instance.py
The final transition from LAUNCHING to RUNNING that is happening in finalizeInstance involves checking whether a container represented by a given Instance is actually running. This operation can take a long time. Instance state can change in the meantime. This commit introduces an additional safety mechanism (reloading state), before any changes are applied.
Additionally, since finalizeInstance is called multiple times for a given job status (i.e. job changes but its status stays the same, but 'jobs.job.update.after' is triggered nevertheless), this commit prevents pointless instace updates with the same status.
See #359
=> Fix instance LAUNCHING->RUNNING transition. Fixes #359

server/constants.py
Renames the stage repository to sandbox.
=> Rename DataONE string

plugin_tests/dataone_register_test.py, plugin_tests/dataverse_test.py, plugin_tests/harvester_test.py, plugin_tests/zenodo_test.py, server/lib/import_item.py
Make sure we're not creating filenames that cannot be used on a POSIX fs.
TODO:
=> Sanitize imported file/folder names. Fixes #381

server/models/tale.py
=> Use correct model for updating aux folder ACL

plugin_tests/manifest_test.py, server/lib/dataone/register.py, server/lib/manifest.py, server/lib/zenodo/provider.py, server/models/tale.py, server/rest/tale.py, server/schema/misc.py
For rationale and discussion see https://github.com/whole-tale/whole-tale/issues/81
see https://github.com/whole-tale/dashboard/pull/595
=> Introduce related identifiers for Tales. Fixes whole-tale/whole-tale#81

server/lib/exporters/bag.py
1. Create a Tale with external data (and something in workspace just for fun)
2. Export as bagit
3. Unzip and run `bagit.py --validate .`
=> [bag] additional files outside of data/ belong to tag-manifest

server/constants.py
I found the way to get straight to DV's api key page...
=> Update DV's docs_href

circle.yml, plugin_tests/import_test.py, plugin_tests/manifest_test.py, plugin_tests/tale_test.py, requirements.txt, server/__init__.py, server/lib/exporters/__init__.py, server/lib/exporters/bag.py, server/lib/exporters/native.py, server/lib/manifest.py, server/rest/tale.py, server/tasks/copy_workspace.py
Convert wholetale plugin to use *virtual resources* for homes and workspaces. Details in testing plan: tba
=> Port workspace related code to virtual_resources

server/models/tale.py
Propagate ACL changes to all auxiliary folders (versions and runs are new).
1. Create a versioned tale. (HINT: `deploy_dev:scripts/create_versioned_tale.py` makes it easy)
2. Share with one user as readonly, and other as rw. (HINT: `deploy_dev:scripts/create_extra_users.py` makes it easy)
3. Confirm in girder that Version and Runs folders (and their content) have proper ACLs.
=> Respect ACLs for versions and runs

plugin_tests/accounts_test.py, plugin_tests/data/dataverse_hierarchy.txt, plugin_tests/dataverse_test.py, plugin_tests/import_test.py, server/__init__.py, server/lib/dataone/register.py, server/lib/dataverse/provider.py, server/lib/exporters/__init__.py, server/lib/manifest.py, server/lib/manifest_parser.py, server/lib/zenodo/integration.py, server/tasks/import_tale.py, server/utils.py
Do not expand root dataset folder in the manifest.
1. Deploy alongside with https://github.com/whole-tale/wt_versioning/pull/13
1. Follow the steps from #439 and confirm that dataset before export == dataset after import.
=> Manifest should only expand subfolders in dataSet. Fixes #439

server/rest/tale.py
1. Using swagger page create a Tale with "authors" missing or set to `None`  (same with e.g. "public" set to `None`)
1. You should get a valid Tale. Before you'd get a Tale with `authors: "Firstname Lastname"` or `public: None` which would break schema internally.
=> Ensure that defaults in Tale creation follow the schema

plugin_tests/import_test.py, requirements.txt, server/tasks/import_binder.py, server/tasks/import_git_repo.py
* Disable cache in places where we do a lot of fast writes
* listdir() now returns a generator instead of a list
* Minor polling optimizations
=> Updates related to fs.webdavfs 0.4.2

circle.yml
A lot of things done in circle.yml is no longer necessary.
=> [circleCI] drop steps that are now part of the image

server/rest/tale.py, server/schema/misc.py, server/schema/tale.py
=> Include imageId in tale's imageInfo

server/constants.py
=> Fix default url for grabbing token from D1

plugin_tests/import_test.py, plugin_tests/instance_test.py, server/models/instance.py
This PR moves the event notification until after the instance (status) has been saved.
=> Send notification after instance update

server/rest/instance.py
a piece required for https://github.com/whole-tale/girder_wholetale/issues/477
=> Update instance.lastActivity everytime authorize is called

server/rest/tale.py
Required for https://github.com/whole-tale/ngx-dashboard/pull/188
=> Relax ACL constrains on GET /tale/:id/access

server/lib/exporters/bag.py
=> fix path in fetch.txt

server/models/instance.py
It takes 30s for instances run on a deployments with FQDN to be accessible, which happens to correspond to the timeout of `_wait_for_server`. What we're doing is roughly:
1. spawn job finish -> let's check if container is up to update instance
1. check if instance exists based on `containerInfo.name` (for 30s)
1. no matter what happens in 2. carry on
1. set the `containerInfo.name` on instance _(oops we need it in 2.)_
It's possible to frontload the operation of setting necessary info on the instance object, before we start hitting `authorize` endpoint
1. Deploy in a place using FQDN (like .stage.wholetale.org)
2. Confirm that instances "launch" faster.
3. It can be also confirm by inspecting girder `info.log`. Prior to this change you should see:
```
[2021-05-27 14:24:16,770] INFO: …
```
=> Reoder ops in finalizeInstance so that /authorize can do its job

plugin_tests/tale_test.py, server/rest/tale.py
See https://github.com/whole-tale/wt_home_dirs/pull/34
=> Move workspace removal to wt_home_dirs (see wt_home_dirs#34)

plugin_tests/tale_test.py, server/lib/manifest.py, server/rest/tale.py
Fixes #513 and #514. Test cases are provided there.
=> Tale config preservation fixes

server/lib/manifest.py, server/lib/manifest_parser.py
https://github.com/whole-tale/serialization-format/pull/5 introduced changes for recorded runs and bumped the vocabulary version.
=> Update manifest to use vocab 1.1

server/rest/tale.py, server/tasks/copy_workspace.py, server/tasks/import_tale.py
Optionally pass `versionId`, which will restore given version of the Tale for the copy.
1. See https://github.com/whole-tale/wt_versioning/pull/43
=> Pass versionId to POST /tale/:id/copy

server/lib/exporters/bag.py
Fixes https://github.com/whole-tale/girder_wholetale/issues/539.   
See https://github.com/whole-tale/girder_wholetale/issues/539 for test case.
=> Mount environment.json in workspace for run-local

plugin_tests/import_test.py, requirements.txt, server/tasks/import_binder.py
This drops webdavfs dependency and fixes #544.
1. Use https://github.com/whole-tale/girderfs/pull/35 along this PR.
1. Import doi:10.7910/DVN/5JJ6OE using the AinWT [bookmarklet](https://wholetale.readthedocs.io/en/latest/users_guide/integration.html#bookmarklet-for-analyze-in-whole-tale)
=> Use OSFS to populate workspace in AinWT

plugin_tests/dataverse_test.py, server/lib/__init__.py, server/lib/data_map.py, server/lib/dataone/provider.py, server/lib/dataverse/provider.py, server/lib/globus/globus_provider.py, server/lib/http_provider.py, server/lib/import_providers.py, server/lib/zenodo/provider.py, server/rest/dataset.py, server/rest/repository.py, server/rest/tale.py, server/tasks/import_binder.py, server/tasks/import_tale.py, server/tasks/register_dataset.py
This fixes all inconsistencies in using `DataMap` throughout the codebase.
1. Follow test steps in #547. NOTE: I had to add image with a proper name "RStudio (R 3.5.1)"
=> Use DataMap consistently. Fixes #547

server/__init__.py
Default `jobInfo` creation for celery tasks doesn't allow to pass an existing token. This PR overrides the default worker event handler and replaces it with a version that consumes `token` field from the job.
=> fix: override jobInfoSpec to allow to pass token

plugin_tests/instance_test.py, server/__init__.py, server/models/instance.py, server/rest/tale.py
Companion to https://github.com/whole-tale/gwvolman/pull/177
Adds 'canceled' state to notifications and fixes handling of chain task revocation.
=> Handle canceling of chain jobs

server/lib/bdbag/bdbag_provider.py
Should be self explanatory and so should be my embarrassment.
=> There can be spaces in file names

plugin_tests/basic_test.py, server/__init__.py, server/constants.py, server/rest/wholetale.py, web_client/templates/configView.pug, web_client/templates/layoutFooter.pug, web_client/views/ConfigView.js, web_client/views/FooterView.js
`About`, `Contact` and `Report a bug` are now configurable from `wholetale` plugin settings page.
=> Allow to configure footer in Girder UI
